[pytest]
pythonpath = .
testpaths = tests
norecursedirs = .git .venv .venv_test venv site-packages dist build
filterwarnings =
    ignore:'crypt' is deprecated and slated for removal in Python 3\.13:DeprecationWarning
    ignore:Support for class-based `config` is deprecated, use ConfigDict instead\.:pydantic.warnings.PydanticDeprecatedSince20
    ignore:`json_encoders` is deprecated\.:pydantic.warnings.PydanticDeprecatedSince20
