CATALOG_STREAM = "catalog-stream"
PAYMENT_STREAM = "payment-stream"
ORDER_STREAM = "order-stream"
WALLET_STREAM = "wallet-stream"
NOTIFICATION_STREAM = "notification-stream"
LOGISTICS_STREAM = "logistics-stream"
MANIFEST_CREATED = "manifest.created"
