CATALOG_STREAM = "catalog-stream"
PAYMENT_STREAM = "payment-stream"
ORDER_STREAM = "order-stream"
WALLET_STREAM = "wallet-stream"
NOTIFICATION_STREAM = "notification-stream"
LOGISTICS_STREAM = "logistics-stream"
MANIFEST_CREATED = "manifest.created"
WALLET_CREDITED = "wallet.credited"
NOTIFICATION_SENT = "notification.sent"

LOGISTICS_STREAM_DLQ = "logistics-stream.dlq"
WALLET_STREAM_DLQ = "wallet-stream.dlq"
NOTIFICATION_STREAM_DLQ = "notification-stream.dlq"
CATALOG_STREAM_DLQ = "catalog-stream.dlq"
PAYMENT_STREAM_DLQ = "payment-stream.dlq"
ORDER_STREAM_DLQ = "order-stream.dlq"
