"""
Players adicionais — carriers, marketplaces, agregadores, food delivery, PUDO retail.

Complementa rental_locker_ecosystem.py; cada rede pode ligar-se a global_players via global_player_code.
"""
from __future__ import annotations

from typing import Any

# market_segment: PARCEL_LOCKER | CARRIER | MARKETPLACE | PUDO_RETAIL | AGGREGATOR | FOOD_DELIVERY

EXTRA_LOCKER_NETWORKS: list[dict[str, Any]] = [
    # —— Carriers globais ——
    {
        "id": "net-ups",
        "code": "UPS",
        "name": "UPS Access Point / Lockers",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "UPS_ACCESS_POINT",
        "hardware_vendor": "UPS",
        "countries": ["US", "CA", "MX", "DE", "FR", "UK"],
        "website_url": "https://www.ups.com",
        "region_group": "GLOBAL",
    },
    {
        "id": "net-fedex",
        "code": "FEDEX",
        "name": "FedEx Ship & Hold / Lockers",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "FEDEX",
        "countries": ["US", "CA", "UK", "DE"],
        "website_url": "https://www.fedex.com",
        "region_group": "GLOBAL",
    },
    {
        "id": "net-gls",
        "code": "GLS",
        "name": "GLS ParcelShops & Lockers",
        "network_type": "LOCKER_NETWORK",
        "market_segment": "CARRIER",
        "global_player_code": "GLS",
        "countries": ["DE", "FR", "NL", "BE", "AT", "IT", "ES"],
        "website_url": "https://gls-group.com",
        "region_group": "EU",
    },
    {
        "id": "net-seur",
        "code": "SEUR",
        "name": "SEUR Pickup & Lockers",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "SEUR",
        "countries": ["ES", "PT"],
        "website_url": "https://www.seur.com",
        "region_group": "EU",
    },
    {
        "id": "net-evri",
        "code": "EVRI",
        "name": "Evri ParcelShops (Hermes UK)",
        "network_type": "LOCKER_NETWORK",
        "market_segment": "CARRIER",
        "global_player_code": "EVRI",
        "countries": ["UK"],
        "website_url": "https://www.evri.com",
        "region_group": "EU",
    },
    {
        "id": "net-yodel",
        "code": "YODEL",
        "name": "Yodel Store-to-Door Lockers",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "YODEL",
        "countries": ["UK"],
        "website_url": "https://www.yodel.co.uk",
        "region_group": "EU",
    },
    {
        "id": "net-postnl",
        "code": "POSTNL",
        "name": "PostNL Pakketautomaten",
        "network_type": "LOCKER_NETWORK",
        "market_segment": "CARRIER",
        "global_player_code": "POSTNL",
        "countries": ["NL"],
        "website_url": "https://www.postnl.nl",
        "region_group": "EU",
    },
    {
        "id": "net-auspost",
        "code": "AU_POST",
        "name": "Australia Post Parcel Lockers",
        "network_type": "LOCKER_NETWORK",
        "market_segment": "CARRIER",
        "global_player_code": "AUSTRALIA_POST",
        "countries": ["AU"],
        "website_url": "https://auspost.com.au",
        "region_group": "APAC",
    },
    {
        "id": "net-jadlog",
        "code": "JADLOG",
        "name": "Jadlog Pontos / Lockers",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "JADLOG",
        "countries": ["BR"],
        "website_url": "https://www.jadlog.com.br",
        "region_group": "AMER",
    },
    {
        "id": "net-loggi",
        "code": "LOGGI",
        "name": "Loggi Pontos",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "LOGGI",
        "countries": ["BR"],
        "website_url": "https://www.loggi.com",
        "region_group": "AMER",
    },
    {
        "id": "net-mondial-relay",
        "code": "MONDIAL_RELAY",
        "name": "Mondial Relay Points Relais",
        "network_type": "COLLECTION_POINT",
        "market_segment": "PUDO_RETAIL",
        "global_player_code": "MONDIAL_RELAY",
        "countries": ["FR", "ES", "BE", "NL"],
        "website_url": "https://www.mondialrelay.com",
        "region_group": "EU",
    },
    {
        "id": "net-pickup-pl",
        "code": "PICKUP_PL",
        "name": "Pickup.pl Parcel Lockers",
        "network_type": "LOCKER_NETWORK",
        "market_segment": "PARCEL_LOCKER",
        "global_player_code": "INPOST",
        "hardware_vendor": "Pickup.pl",
        "countries": ["PL"],
        "website_url": "https://pickup.pl",
        "region_group": "EU",
    },
    # —— Marketplaces ——
    {
        "id": "net-walmart",
        "code": "WALMART",
        "name": "Walmart Pickup / Locker",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "WALMART",
        "countries": ["US", "MX"],
        "website_url": "https://www.walmart.com",
        "region_group": "AMER",
    },
    {
        "id": "net-shopee",
        "code": "SHOPEE",
        "name": "Shopee / SPX Lockers",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "SHOPEE",
        "countries": ["BR", "SG", "ID", "TH", "VN"],
        "website_url": "https://shopee.com",
        "region_group": "APAC",
    },
    {
        "id": "net-shein",
        "code": "SHEIN",
        "name": "SHEIN Collection Points",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "SHEIN",
        "countries": ["BR", "US", "EU"],
        "website_url": "https://www.shein.com",
        "region_group": "GLOBAL",
    },
    {
        "id": "net-temu",
        "code": "TEMU",
        "name": "Temu Pickup Points",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "TEMU",
        "countries": ["US", "EU", "BR"],
        "website_url": "https://www.temu.com",
        "region_group": "GLOBAL",
    },
    {
        "id": "net-tiktok-shop",
        "code": "TIKTOK_SHOP",
        "name": "TikTok Shop Logistics Hubs",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "TIKTOK_SHOP",
        "countries": ["US", "UK", "ID", "BR"],
        "website_url": "https://shop.tiktok.com",
        "region_group": "GLOBAL",
    },
    {
        "id": "net-otto",
        "code": "OTTO",
        "name": "OTTO Abholstationen",
        "network_type": "COLLECTION_POINT",
        "market_segment": "MARKETPLACE",
        "global_player_code": "OTTO",
        "countries": ["DE", "AT"],
        "website_url": "https://www.otto.de",
        "region_group": "EU",
    },
    {
        "id": "net-cdiscount",
        "code": "CDISCOUNT",
        "name": "Cdiscount Points Relais",
        "network_type": "COLLECTION_POINT",
        "market_segment": "MARKETPLACE",
        "global_player_code": "CDISCOUNT",
        "countries": ["FR"],
        "website_url": "https://www.cdiscount.com",
        "region_group": "EU",
    },
    {
        "id": "net-flipkart",
        "code": "FLIPKART",
        "name": "Flipkart Pickup Lockers",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "FLIPKART",
        "countries": ["IN"],
        "website_url": "https://www.flipkart.com",
        "region_group": "APAC",
    },
    {
        "id": "net-lazada",
        "code": "LAZADA",
        "name": "Lazada Logistics / Lockers",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "LAZADA",
        "countries": ["SG", "MY", "TH", "VN", "PH", "ID"],
        "website_url": "https://www.lazada.com",
        "region_group": "APAC",
    },
    {
        "id": "net-tokopedia",
        "code": "TOKOPEDIA",
        "name": "Tokopedia / TikTok Shop ID Lockers",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "TOKOPEDIA",
        "countries": ["ID"],
        "website_url": "https://www.tokopedia.com",
        "region_group": "APAC",
    },
    {
        "id": "net-rakuten",
        "code": "RAKUTEN",
        "name": "Rakuten Haco Post / Lockers",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "RAKUTEN",
        "countries": ["JP"],
        "website_url": "https://www.rakuten.co.jp",
        "region_group": "APAC",
    },
    {
        "id": "net-zalando",
        "code": "ZALANDO",
        "name": "Zalando Pickup Points",
        "network_type": "COLLECTION_POINT",
        "market_segment": "MARKETPLACE",
        "global_player_code": "ZALANDO",
        "countries": ["DE", "FR", "IT", "ES", "NL"],
        "website_url": "https://www.zalando.com",
        "region_group": "EU",
    },
    {
        "id": "net-allegro",
        "code": "ALLEGRO",
        "name": "Allegro One Box / Lockers",
        "network_type": "MARKETPLACE_HUB",
        "market_segment": "MARKETPLACE",
        "global_player_code": "ALLEGRO",
        "countries": ["PL", "CZ", "SK"],
        "website_url": "https://allegro.pl",
        "region_group": "EU",
    },
    # —— Agregadores / hubs logísticos ——
    {
        "id": "net-melhor-envio",
        "code": "MELHOR_ENVIO",
        "name": "Melhor Envio — rede agregada",
        "network_type": "AGGREGATOR",
        "market_segment": "AGGREGATOR",
        "global_player_code": "MELHOR_ENVIO",
        "countries": ["BR"],
        "website_url": "https://melhorenvio.com.br",
        "region_group": "AMER",
    },
    {
        "id": "net-intelipost",
        "code": "INTELIPOST",
        "name": "Intelipost TMS / Lockers",
        "network_type": "AGGREGATOR",
        "market_segment": "AGGREGATOR",
        "global_player_code": "INTELIPOST",
        "countries": ["BR"],
        "website_url": "https://www.intelipost.com.br",
        "region_group": "AMER",
    },
    {
        "id": "net-easypost",
        "code": "EASYPOST",
        "name": "EasyPost Carrier Network",
        "network_type": "AGGREGATOR",
        "market_segment": "AGGREGATOR",
        "global_player_code": "EASYPOST",
        "countries": ["US", "CA"],
        "website_url": "https://www.easypost.com",
        "region_group": "AMER",
    },
    {
        "id": "net-shippo",
        "code": "SHIPPO",
        "name": "Shippo Multi-Carrier Hub",
        "network_type": "AGGREGATOR",
        "market_segment": "AGGREGATOR",
        "global_player_code": "SHIPPO",
        "countries": ["US", "EU"],
        "website_url": "https://goshippo.com",
        "region_group": "GLOBAL",
    },
    {
        "id": "net-parcel2go",
        "code": "PARCEL2GO",
        "name": "Parcel2Go Comparison / Pickup",
        "network_type": "AGGREGATOR",
        "market_segment": "AGGREGATOR",
        "global_player_code": None,
        "countries": ["UK"],
        "website_url": "https://www.parcel2go.com",
        "region_group": "EU",
    },
    # —— Food delivery (handoff em locker / dark store) ——
    {
        "id": "net-ifood",
        "code": "IFOOD",
        "name": "iFood — retirada em locker",
        "network_type": "COLLECTION_POINT",
        "market_segment": "FOOD_DELIVERY",
        "global_player_code": "IFOOD",
        "countries": ["BR"],
        "website_url": "https://www.ifood.com.br",
        "region_group": "AMER",
    },
    {
        "id": "net-uber-eats",
        "code": "UBER_EATS",
        "name": "Uber Eats Locker Pickup",
        "network_type": "COLLECTION_POINT",
        "market_segment": "FOOD_DELIVERY",
        "global_player_code": "UBER_EATS",
        "countries": ["US", "BR", "MX", "FR", "UK"],
        "website_url": "https://www.ubereats.com",
        "region_group": "GLOBAL",
    },
    {
        "id": "net-glovo",
        "code": "GLOVO",
        "name": "Glovo Parcel / Locker Points",
        "network_type": "COLLECTION_POINT",
        "market_segment": "FOOD_DELIVERY",
        "global_player_code": "GLOVO",
        "countries": ["ES", "PT", "IT", "PL"],
        "website_url": "https://glovoapp.com",
        "region_group": "EU",
    },
    {
        "id": "net-deliveroo",
        "code": "DELIVEROO",
        "name": "Deliveroo Editions / Pickup",
        "network_type": "COLLECTION_POINT",
        "market_segment": "FOOD_DELIVERY",
        "global_player_code": "DELIVEROO",
        "countries": ["UK", "FR", "IT", "IE"],
        "website_url": "https://deliveroo.com",
        "region_group": "EU",
    },
    {
        "id": "net-rappi",
        "code": "RAPPI",
        "name": "Rappi Turbo Lockers",
        "network_type": "COLLECTION_POINT",
        "market_segment": "FOOD_DELIVERY",
        "global_player_code": "RAPPI",
        "countries": ["CO", "MX", "BR", "AR"],
        "website_url": "https://www.rappi.com",
        "region_group": "AMER",
    },
    {
        "id": "net-doordash",
        "code": "DOORDASH",
        "name": "DoorDash Parcel / Hub Lockers",
        "network_type": "COLLECTION_POINT",
        "market_segment": "FOOD_DELIVERY",
        "global_player_code": "DOORDASH",
        "countries": ["US", "CA", "AU"],
        "website_url": "https://www.doordash.com",
        "region_group": "AMER",
    },
    # —— LATAM carriers ——
    {
        "id": "net-total-express",
        "code": "TOTAL_EXPRESS",
        "name": "Total Express",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "TOTAL_EXPRESS",
        "countries": ["AR", "CL"],
        "website_url": "https://www.totalexpress.com.ar",
        "region_group": "AMER",
    },
    {
        "id": "net-oca",
        "code": "OCA",
        "name": "OCA e-Pak / Puntos OCA",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "OCA",
        "countries": ["AR"],
        "website_url": "https://www.oca.com.ar",
        "region_group": "AMER",
    },
    {
        "id": "net-andreani",
        "code": "ANDREANI",
        "name": "Andreani Puntos de Retiro",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "ANDREANI",
        "countries": ["AR"],
        "website_url": "https://www.andreani.com",
        "region_group": "AMER",
    },
    {
        "id": "net-chilexpress",
        "code": "CHILEXPRESS",
        "name": "Chilexpress Pickup",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "CHILEXPRESS",
        "countries": ["CL"],
        "website_url": "https://www.chilexpress.cl",
        "region_group": "AMER",
    },
    {
        "id": "net-bluex",
        "code": "BLUEX",
        "name": "Blue Express Lockers / Puntos",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "BLUEX",
        "countries": ["CL"],
        "website_url": "https://www.blue.cl",
        "region_group": "AMER",
    },
    {
        "id": "net-estafeta",
        "code": "ESTAFETA",
        "name": "Estafeta Punto Cercano",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "ESTAFETA",
        "countries": ["MX"],
        "website_url": "https://www.estafeta.com",
        "region_group": "AMER",
    },
    {
        "id": "net-servientrega",
        "code": "SERVIENTREGA",
        "name": "Servientrega Puntos",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "SERVIENTREGA",
        "countries": ["CO", "EC", "PE"],
        "website_url": "https://www.servientrega.com",
        "region_group": "AMER",
    },
    {
        "id": "net-paqueteexpress",
        "code": "PAQUETEXPRESS",
        "name": "Paquetexpress Pickup",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "PAQUETEXPRESS",
        "countries": ["MX"],
        "website_url": "https://www.paquetexpress.com.mx",
        "region_group": "AMER",
    },
    {
        "id": "net-redpack",
        "code": "REDPACK",
        "name": "Redpack Punto Redpack",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "REDPACK",
        "countries": ["MX"],
        "website_url": "https://www.redpack.com.mx",
        "region_group": "AMER",
    },
    {
        "id": "net-pickit",
        "code": "PICKIT",
        "name": "Pickit Smart Lockers / Puntos",
        "network_type": "LOCKER_NETWORK",
        "market_segment": "PARCEL_LOCKER",
        "global_player_code": "PICKIT",
        "countries": ["AR", "MX", "CL", "UY"],
        "website_url": "https://pickit.com.ar",
        "region_group": "AMER",
    },
    # —— APAC networks ——
    {
        "id": "net-sf-express",
        "code": "SF_EXPRESS",
        "name": "SF Express / Fengchao Lockers",
        "network_type": "LOCKER_NETWORK",
        "market_segment": "CARRIER",
        "global_player_code": "SF_EXPRESS",
        "hardware_vendor": "SF Holding",
        "countries": ["CN", "HK", "SG"],
        "website_url": "https://www.sf-express.com",
        "region_group": "APAC",
    },
    {
        "id": "net-yamato",
        "code": "YAMATO",
        "name": "Yamato Transport (Kuroneko)",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "YAMATO",
        "hardware_vendor": "Yamato",
        "countries": ["JP"],
        "website_url": "https://www.kuronekoyamato.co.jp",
        "region_group": "APAC",
    },
    {
        "id": "net-yamato-pack",
        "code": "YAMATO_PACK",
        "name": "Yamato Pack Station / PUDO",
        "network_type": "COLLECTION_POINT",
        "market_segment": "PARCEL_LOCKER",
        "global_player_code": "YAMATO",
        "hardware_vendor": "Yamato",
        "countries": ["JP"],
        "website_url": "https://www.kuronekoyamato.co.jp",
        "region_group": "APAC",
    },
    {
        "id": "net-jt-express",
        "code": "JT_EXPRESS",
        "name": "J&T Express Parcel Lockers",
        "network_type": "LOCKER_NETWORK",
        "market_segment": "CARRIER",
        "global_player_code": "JT_EXPRESS",
        "countries": ["CN", "ID", "TH", "VN", "PH", "MY"],
        "website_url": "https://www.jtexpress.com",
        "region_group": "APAC",
    },
    {
        "id": "net-sagawa",
        "code": "SAGAWA",
        "name": "Sagawa Express Hikyaku Bin",
        "network_type": "CARRIER_OPERATED",
        "market_segment": "CARRIER",
        "global_player_code": "SAGAWA",
        "countries": ["JP"],
        "website_url": "https://www.sagawa-exp.co.jp",
        "region_group": "APAC",
    },
]

# Mapeamento código rede rental → global_players.code (redes base + extras)
NETWORK_GLOBAL_PLAYER_CODES: dict[str, str] = {
    "INPOST": "INPOST",
    "DPD": "DPD",
    "DHL_PACK": "DHL_PACKSTATION",
    "DHL": "DHL_PARCEL",
    "ROYALMAIL": "ROYAL_MAIL",
    "LAPOSTE": "LA_POSTE",
    "COLISSIMO": "COLISSIMO",
    "HERMES": "HERMES_DE",
    "CTT": "CTT",
    "WORTEN": "WORTEN",
    "ECI": "EL_CORTE_INGLES",
    "PACKETA": "PACKETA",
    "VINTED_GO": "VINTED_GO",
    "BLOQIT": "BLOQIT",
    "SWIPBOX": "SWIPBOX",
    "CLEVERON": "CLEVERON",
    "BRING": "BRING",
    "POSTNORD": "POSTNORD",
    "SWISSPOST": "SWISS_POST",
    "CORREIOS": "CORREIOS",
    "MAGALU": "MAGALU",
    "MELI": "MERCADO_LIVRE",
    "AMAZON_HUB": "AMAZON_HUB",
    "USPS": "USPS",
    "CAINIAO": "CAINIAO",
    "QUADIENT": "QUADIENT",
    **{n["code"]: n["global_player_code"] for n in EXTRA_LOCKER_NETWORKS if n.get("global_player_code")},
}

# (from_code, to_code, relation_type, integration_mode)
# relation_type: INTERCONNECT | MARKETPLACE_ROUTING | AGGREGATOR_ROUTING | FOOD_HANDOFF | WHITELABEL
ECOSYSTEM_NETWORK_RELATIONS: list[tuple[str, str, str, str]] = [
    ("INPOST", "DPD", "INTERCONNECT", "API"),
    ("INPOST", "ROYALMAIL", "INTERCONNECT", "EDI"),
    ("DPD", "GLS", "INTERCONNECT", "API"),
    ("DHL_PACK", "DHL", "WHITELABEL", "INTERNAL"),
    ("MELI", "CORREIOS", "MARKETPLACE_ROUTING", "WEBHOOK"),
    ("MELI", "JADLOG", "MARKETPLACE_ROUTING", "API"),
    ("MAGALU", "CORREIOS", "MARKETPLACE_ROUTING", "API"),
    ("AMAZON_HUB", "UPS", "MARKETPLACE_ROUTING", "API"),
    ("SHOPEE", "CAINIAO", "MARKETPLACE_ROUTING", "API"),
    ("SHEIN", "CAINIAO", "MARKETPLACE_ROUTING", "API"),
    ("TEMU", "CAINIAO", "AGGREGATOR_ROUTING", "API"),
    ("MELHOR_ENVIO", "CORREIOS", "AGGREGATOR_ROUTING", "API"),
    ("MELHOR_ENVIO", "JADLOG", "AGGREGATOR_ROUTING", "API"),
    ("MELHOR_ENVIO", "LOGGI", "AGGREGATOR_ROUTING", "API"),
    ("INTELIPOST", "MELI", "AGGREGATOR_ROUTING", "WEBHOOK"),
    ("EASYPOST", "USPS", "AGGREGATOR_ROUTING", "API"),
    ("EASYPOST", "FEDEX", "AGGREGATOR_ROUTING", "API"),
    ("SHIPPO", "UPS", "AGGREGATOR_ROUTING", "API"),
    ("CAINIAO", "CORREIOS", "AGGREGATOR_ROUTING", "EDI"),
    ("IFOOD", "MAGALU", "FOOD_HANDOFF", "WEBHOOK"),
    ("UBER_EATS", "AMAZON_HUB", "FOOD_HANDOFF", "API"),
    ("GLOVO", "MONDIAL_RELAY", "FOOD_HANDOFF", "MANUAL"),
    ("WORTEN", "CTT", "INTERCONNECT", "API"),
    ("ECI", "SEUR", "INTERCONNECT", "API"),
    ("WALMART", "FEDEX", "MARKETPLACE_ROUTING", "API"),
    ("FLIPKART", "CAINIAO", "MARKETPLACE_ROUTING", "API"),
    ("MELI", "OCA", "MARKETPLACE_ROUTING", "API"),
    ("MELI", "ANDREANI", "MARKETPLACE_ROUTING", "API"),
    ("MELI", "TOTAL_EXPRESS", "MARKETPLACE_ROUTING", "API"),
    ("MELI", "CHILEXPRESS", "MARKETPLACE_ROUTING", "API"),
    ("MELI", "ESTAFETA", "MARKETPLACE_ROUTING", "API"),
    ("MELI", "SERVIENTREGA", "MARKETPLACE_ROUTING", "WEBHOOK"),
    ("SF_EXPRESS", "CAINIAO", "INTERCONNECT", "API"),
    ("YAMATO", "YAMATO_PACK", "WHITELABEL", "INTERNAL"),
    ("RAKUTEN", "YAMATO", "MARKETPLACE_ROUTING", "API"),
    ("SHOPEE", "JT_EXPRESS", "MARKETPLACE_ROUTING", "API"),
    ("IFOOD", "WORTEN", "FOOD_HANDOFF", "WEBHOOK"),
    ("RAPPI", "MAGALU", "FOOD_HANDOFF", "WEBHOOK"),
    ("UBER_EATS", "WORTEN", "FOOD_HANDOFF", "API"),
    ("UBER_EATS", "ECI", "FOOD_HANDOFF", "API"),
    ("DELIVEROO", "ECI", "FOOD_HANDOFF", "WEBHOOK"),
    ("GLOVO", "WORTEN", "FOOD_HANDOFF", "API"),
    ("GLOVO", "ECI", "FOOD_HANDOFF", "API"),
    ("DOORDASH", "WALMART", "FOOD_HANDOFF", "API"),
    ("MELI", "REDPACK", "MARKETPLACE_ROUTING", "API"),
    ("MELI", "PICKIT", "MARKETPLACE_ROUTING", "API"),
    ("PICKIT", "OCA", "INTERCONNECT", "API"),
    ("PICKIT", "REDPACK", "INTERCONNECT", "API"),
    ("RAPPI", "PICKIT", "FOOD_HANDOFF", "WEBHOOK"),
    ("WALMART", "REDPACK", "MARKETPLACE_ROUTING", "API"),
    ("LAZADA", "CAINIAO", "MARKETPLACE_ROUTING", "API"),
    ("LAZADA", "JT_EXPRESS", "MARKETPLACE_ROUTING", "API"),
    ("TOKOPEDIA", "JT_EXPRESS", "MARKETPLACE_ROUTING", "API"),
    ("TOKOPEDIA", "CAINIAO", "MARKETPLACE_ROUTING", "API"),
]

EXTRA_ECOSYSTEM_PLANS: list[dict[str, Any]] = [
    {
        "id": "rental-plan-shopee-br",
        "network_id": "net-shopee",
        "slot_size": "M",
        "name": "Shopee SPX — locker M",
        "billing_cycle": "MONTHLY",
        "amount_cents": 10500,
    },
    {
        "id": "rental-plan-melhor-envio",
        "network_id": "net-melhor-envio",
        "slot_size": "S",
        "name": "Melhor Envio — slot agregador",
        "billing_cycle": "MONTHLY",
        "amount_cents": 6900,
    },
    {
        "id": "rental-plan-ifood-locker",
        "network_id": "net-ifood",
        "slot_size": "S",
        "name": "iFood — handoff locker",
        "billing_cycle": "WEEKLY",
        "amount_cents": 3900,
    },
    {
        "id": "rental-plan-ups-access",
        "network_id": "net-ups",
        "slot_size": "M",
        "name": "UPS Access Point — M",
        "billing_cycle": "MONTHLY",
        "amount_cents": 13500,
    },
]

EXTRA_ECOSYSTEM_OPERATORS: list[dict[str, Any]] = [
    {
        "id": "op-shopee-br",
        "tenant_id": "tenant-shopee",
        "network_id": "net-shopee",
        "legal_name": "Shopee Brasil",
        "operator_code": "SHOPEE_BR",
        "commission_bps": 510,
    },
    {
        "id": "op-melhor-envio",
        "tenant_id": "tenant-melhor-envio",
        "network_id": "net-melhor-envio",
        "legal_name": "Melhor Envio",
        "operator_code": "MELHOR_ENVIO",
        "commission_bps": 380,
    },
    {
        "id": "op-ifood",
        "tenant_id": "tenant-ifood",
        "network_id": "net-ifood",
        "legal_name": "iFood.com Agência de Restaurantes",
        "operator_code": "IFOOD_BR",
        "commission_bps": 550,
    },
]

EXTRA_WEBHOOK_TENANTS: list[str] = [
    "tenant-shopee",
    "tenant-melhor-envio",
    "tenant-ifood",
    "tenant-ups",
]
