"""
Registro mundial de players locker / carrier / marketplace / PUDO para assinaturas.

Fonte única usada pelo catálogo OPS, seed de partner_programs e plan entitlements.
"""
from __future__ import annotations

from typing import Any

# Códigos destacados na revisão de produto (lockers + marketplaces + carriers IBÉRIA/BR)
PRIORITY_PLAYER_CODES: frozenset[str] = frozenset(
    {
        "inpost",
        "dhl",
        "magalu",
        "mercado_livre",
        "amazon",
        "dpd",
        "correios",
        "ctt",
        "worten",
        "el_corte_ingles",
    }
)

# code, name, player_type, segment, regions, default_plan, revenue_share_pct, tier_eligibility
GLOBAL_SUBSCRIPTION_PLAYERS: list[dict[str, Any]] = [
    # —— Prioridade explícita (locker / marketplace / carrier) ——
    {
        "code": "inpost",
        "name": "InPost",
        "player_type": "LOCKER_OPERATOR",
        "segment": "PARCEL_LOCKER",
        "regions": ["PL", "UK", "FR", "IT", "ES"],
        "default_plan": "PRO",
        "revenue_share_pct": 5.0,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://inpost.pl",
    },
    {
        "code": "dhl",
        "name": "DHL Packstation",
        "player_type": "LOCKER_OPERATOR",
        "segment": "PARCEL_LOCKER",
        "regions": ["DE", "AT", "NL", "BE", "CZ"],
        "default_plan": "PRO",
        "revenue_share_pct": 6.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://www.dhl.de",
    },
    {
        "code": "dpd",
        "name": "DPD Parcel Lockers",
        "player_type": "LOCKER_OPERATOR",
        "segment": "PARCEL_LOCKER",
        "regions": ["DE", "FR", "UK", "PL", "ES", "PT"],
        "default_plan": "PRO",
        "revenue_share_pct": 5.5,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://www.dpd.com",
    },
    {
        "code": "magalu",
        "name": "Magalu",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["BR"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 8.5,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://www.magazineluiza.com.br",
    },
    {
        "code": "mercado_livre",
        "name": "Mercado Livre",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["BR", "AR", "MX", "CL", "CO"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 7.0,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://www.mercadolivre.com.br",
    },
    {
        "code": "amazon",
        "name": "Amazon Hub Locker",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["US", "UK", "DE", "FR", "IT", "ES"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 4.5,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://www.amazon.com",
    },
    {
        "code": "correios",
        "name": "Correios",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["BR"],
        "default_plan": "BASIC",
        "revenue_share_pct": 3.0,
        "tier_eligibility": ["BASIC", "PREMIUM", "PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://www.correios.com.br",
    },
    {
        "code": "ctt",
        "name": "CTT",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["PT"],
        "default_plan": "BASIC",
        "revenue_share_pct": 3.0,
        "tier_eligibility": ["BASIC", "PREMIUM", "PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://www.ctt.pt",
    },
    {
        "code": "worten",
        "name": "Worten",
        "player_type": "COLLECTION_POINT",
        "segment": "PUDO_RETAIL",
        "regions": ["PT", "ES"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://www.worten.pt",
    },
    {
        "code": "el_corte_ingles",
        "name": "El Corte Inglés",
        "player_type": "COLLECTION_POINT",
        "segment": "PUDO_RETAIL",
        "regions": ["ES", "PT"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": True,
        "website": "https://www.elcorteingles.es",
    },
    # —— Redes locker / hardware ——
    {
        "code": "swipbox",
        "name": "SwipBox",
        "player_type": "HARDWARE",
        "segment": "HARDWARE_VENDOR",
        "regions": ["EU", "NORDICS"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 2.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "cleveron",
        "name": "Cleveron",
        "player_type": "HARDWARE",
        "segment": "HARDWARE_VENDOR",
        "regions": ["GLOBAL"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 2.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "quadient",
        "name": "Quadient",
        "player_type": "HARDWARE",
        "segment": "HARDWARE_VENDOR",
        "regions": ["EU", "US"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 2.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "packeta",
        "name": "Packeta / Zásilkovna",
        "player_type": "LOCKER_OPERATOR",
        "segment": "PARCEL_LOCKER",
        "regions": ["CZ", "SK", "HU", "RO"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.5,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "vinted_go",
        "name": "Vinted Go",
        "player_type": "LOCKER_OPERATOR",
        "segment": "PARCEL_LOCKER",
        "regions": ["FR", "NL", "BE", "ES"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "bloq_it",
        "name": "Bloq.it",
        "player_type": "HARDWARE",
        "segment": "HARDWARE_VENDOR",
        "regions": ["EU"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 2.5,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "pickup_pl",
        "name": "Pickup (PL)",
        "player_type": "LOCKER_OPERATOR",
        "segment": "PARCEL_LOCKER",
        "regions": ["PL"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PREMIUM", "PRO"],
        "priority": False,
    },
    # —— Carriers globais ——
    {
        "code": "usps",
        "name": "USPS",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["US"],
        "default_plan": "PRO",
        "revenue_share_pct": 3.5,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "royal_mail",
        "name": "Royal Mail",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["UK"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "la_poste",
        "name": "La Poste",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["FR"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "colissimo",
        "name": "Colissimo",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["FR"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "hermes_de",
        "name": "Hermes DE",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["DE"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "yodel",
        "name": "Yodel",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["UK"],
        "default_plan": "PRO",
        "revenue_share_pct": 3.5,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "swiss_post",
        "name": "Swiss Post",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["CH"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "postnord",
        "name": "PostNord",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["SE", "DK", "NO", "FI"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "australia_post",
        "name": "Australia Post",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["AU"],
        "default_plan": "PRO",
        "revenue_share_pct": 3.5,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "seur",
        "name": "SEUR",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["ES", "PT"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    # —— Marketplaces & PUDO adicionais ——
    {
        "code": "walmart",
        "name": "Walmart Hub",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["US", "MX"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "shopee",
        "name": "Shopee",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["BR", "SEA"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 6.5,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "temu",
        "name": "Temu",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["GLOBAL"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 5.0,
        "tier_eligibility": ["PREMIUM", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "tiktok_shop",
        "name": "TikTok Shop",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["GLOBAL"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 6.0,
        "tier_eligibility": ["PREMIUM", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "rakuten",
        "name": "Rakuten",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["JP", "FR"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "cdiscount",
        "name": "Cdiscount",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["FR"],
        "default_plan": "PRO",
        "revenue_share_pct": 5.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "otto",
        "name": "OTTO",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["DE"],
        "default_plan": "PRO",
        "revenue_share_pct": 5.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "flipkart",
        "name": "Flipkart",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["IN"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 4.5,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    # —— Agregadores / hubs ——
    {
        "code": "cainiao",
        "name": "Cainiao",
        "player_type": "AGGREGATOR",
        "segment": "AGGREGATOR",
        "regions": ["CN", "GLOBAL"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 3.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "intelipost",
        "name": "Intelipost",
        "player_type": "AGGREGATOR",
        "segment": "AGGREGATOR",
        "regions": ["BR"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 3.5,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "melhor_envio",
        "name": "Melhor Envio",
        "player_type": "AGGREGATOR",
        "segment": "AGGREGATOR",
        "regions": ["BR"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "shippo",
        "name": "Shippo",
        "player_type": "AGGREGATOR",
        "segment": "AGGREGATOR",
        "regions": ["US"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 3.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "easypost",
        "name": "EasyPost",
        "player_type": "AGGREGATOR",
        "segment": "AGGREGATOR",
        "regions": ["US"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 3.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "parcel2go",
        "name": "Parcel2Go",
        "player_type": "AGGREGATOR",
        "segment": "AGGREGATOR",
        "regions": ["UK"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 3.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    # —— Redes locker / operadores adicionais ——
    {
        "code": "mondial_relay",
        "name": "Mondial Relay",
        "player_type": "LOCKER_OPERATOR",
        "segment": "PARCEL_LOCKER",
        "regions": ["FR", "ES", "BE"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.5,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "gls",
        "name": "GLS",
        "player_type": "LOCKER_OPERATOR",
        "segment": "PARCEL_LOCKER",
        "regions": ["DE", "FR", "NL", "BE", "IT"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.5,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "evri",
        "name": "Evri (Hermes UK)",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["UK"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "postnl",
        "name": "PostNL",
        "player_type": "LOCKER_OPERATOR",
        "segment": "PARCEL_LOCKER",
        "regions": ["NL"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "bring",
        "name": "Bring",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["NO", "SE", "DK"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "jadlog",
        "name": "Jadlog",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["BR"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "loggi",
        "name": "Loggi",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["BR"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.5,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "fedex",
        "name": "FedEx",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["US", "GLOBAL"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 3.5,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "ups",
        "name": "UPS Access Point",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["US", "EU"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 3.5,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "blue_dart",
        "name": "Blue Dart",
        "player_type": "CARRIER",
        "segment": "CARRIER",
        "regions": ["IN"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 3.5,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    # —— Redes de pontos de coleta ——
    {
        "code": "ponto_magalu",
        "name": "Ponto Magalu",
        "player_type": "COLLECTION_POINT",
        "segment": "PUDO_RETAIL",
        "regions": ["BR"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 5.0,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "shein",
        "name": "Shein",
        "player_type": "MARKETPLACE",
        "segment": "MARKETPLACE",
        "regions": ["GLOBAL"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 5.5,
        "tier_eligibility": ["PREMIUM", "ENTERPRISE"],
        "priority": False,
    },
    # —— Food delivery (handoff locker/PUDO) ——
    {
        "code": "ifood",
        "name": "iFood",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["BR"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 6.0,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": False,
        "integration_modes": ["WEBHOOK", "API"],
    },
    {
        "code": "rappi",
        "name": "Rappi",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["BR", "MX", "CO", "AR"],
        "default_plan": "PREMIUM",
        "revenue_share_pct": 5.5,
        "tier_eligibility": ["PREMIUM", "PRO", "ENTERPRISE"],
        "priority": False,
        "integration_modes": ["WEBHOOK", "API"],
    },
    {
        "code": "uber_eats",
        "name": "Uber Eats",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["GLOBAL"],
        "default_plan": "PRO",
        "revenue_share_pct": 5.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
        "integration_modes": ["API", "OAUTH"],
    },
    {
        "code": "glovo",
        "name": "Glovo",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["ES", "PT", "IT", "PL"],
        "default_plan": "PRO",
        "revenue_share_pct": 5.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "deliveroo",
        "name": "Deliveroo",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["UK", "FR", "IT"],
        "default_plan": "PRO",
        "revenue_share_pct": 5.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "doordash",
        "name": "DoorDash",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["US", "CA", "AU"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 4.5,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "just_eat",
        "name": "Just Eat Takeaway",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["UK", "DE", "NL"],
        "default_plan": "PRO",
        "revenue_share_pct": 4.5,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "grabfood",
        "name": "GrabFood",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["SEA"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "foodpanda",
        "name": "foodpanda",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["SEA", "EU"],
        "default_plan": "ENTERPRISE",
        "revenue_share_pct": 4.0,
        "tier_eligibility": ["ENTERPRISE"],
        "priority": False,
    },
    {
        "code": "pedidos_ya",
        "name": "PedidosYa",
        "player_type": "FOOD_DELIVERY",
        "segment": "FOOD_DELIVERY",
        "regions": ["LATAM"],
        "default_plan": "PRO",
        "revenue_share_pct": 5.0,
        "tier_eligibility": ["PRO", "ENTERPRISE"],
        "priority": False,
    },
]


def tier_player_map_from_registry() -> dict[str, list[str]]:
    tiers = {"BASIC": [], "PREMIUM": [], "PRO": [], "ENTERPRISE": []}
    for p in GLOBAL_SUBSCRIPTION_PLAYERS:
        for tier in p.get("tier_eligibility") or []:
            if tier in tiers and p["code"] not in tiers[tier]:
                tiers[tier].append(p["code"])
    return tiers


def players_by_segment() -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    for p in GLOBAL_SUBSCRIPTION_PLAYERS:
        seg = str(p.get("segment") or "OTHER")
        out.setdefault(seg, []).append(p)
    return out


def players_by_region() -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for p in GLOBAL_SUBSCRIPTION_PLAYERS:
        for reg in p.get("regions") or []:
            out.setdefault(reg, []).append(p["code"])
    return out


def priority_players_payload() -> list[dict[str, Any]]:
    return [p for p in GLOBAL_SUBSCRIPTION_PLAYERS if p.get("priority") or p["code"] in PRIORITY_PLAYER_CODES]
