BEGIN;

-- Insere todos os países soberanos restantes, com is_active = FALSE
-- Omitimos 'id' para usar a sequência/serial da tabela
-- Usamos ON CONFLICT para evitar duplicatas caso o script rode mais de uma vez
INSERT INTO public.capability_country (
    code, name, continent, default_currency, default_timezone, 
    address_format, metadata_json, is_active, created_at, updated_at
) VALUES 
-- África
('DZ', 'Algeria', 'Africa', 'DZD', 'Africa/Algiers', 'DZ', NULL, FALSE, NOW(), NOW()),
('AO', 'Angola', 'Africa', 'AOA', 'Africa/Luanda', 'AO', NULL, FALSE, NOW(), NOW()),
('BJ', 'Benin', 'Africa', 'XOF', 'Africa/Porto-Novo', 'BJ', NULL, FALSE, NOW(), NOW()),
('BW', 'Botswana', 'Africa', 'BWP', 'Africa/Gaborone', 'BW', NULL, FALSE, NOW(), NOW()),
('BF', 'Burkina Faso', 'Africa', 'XOF', 'Africa/Ouagadougou', 'BF', NULL, FALSE, NOW(), NOW()),
('BI', 'Burundi', 'Africa', 'BIF', 'Africa/Bujumbura', 'BI', NULL, FALSE, NOW(), NOW()),
('CV', 'Cape Verde', 'Africa', 'CVE', 'Atlantic/Cape_Verde', 'CV', NULL, FALSE, NOW(), NOW()),
('CM', 'Cameroon', 'Africa', 'XAF', 'Africa/Douala', 'CM', NULL, FALSE, NOW(), NOW()),
('CF', 'Central African Republic', 'Africa', 'XAF', 'Africa/Bangui', 'CF', NULL, FALSE, NOW(), NOW()),
('TD', 'Chad', 'Africa', 'XAF', 'Africa/Ndjamena', 'TD', NULL, FALSE, NOW(), NOW()),
('KM', 'Comoros', 'Africa', 'KMF', 'Indian/Comoro', 'KM', NULL, FALSE, NOW(), NOW()),
('CG', 'Congo', 'Africa', 'XAF', 'Africa/Brazzaville', 'CG', NULL, FALSE, NOW(), NOW()),
('CD', 'Democratic Republic of the Congo', 'Africa', 'CDF', 'Africa/Kinshasa', 'CD', NULL, FALSE, NOW(), NOW()),
('CI', 'Ivory Coast', 'Africa', 'XOF', 'Africa/Abidjan', 'CI', NULL, FALSE, NOW(), NOW()),
('DJ', 'Djibouti', 'Africa', 'DJF', 'Africa/Djibouti', 'DJ', NULL, FALSE, NOW(), NOW()),
('EG', 'Egypt', 'Africa', 'EGP', 'Africa/Cairo', 'EG', NULL, FALSE, NOW(), NOW()),
('GQ', 'Equatorial Guinea', 'Africa', 'XAF', 'Africa/Malabo', 'GQ', NULL, FALSE, NOW(), NOW()),
('ER', 'Eritrea', 'Africa', 'ERN', 'Africa/Asmara', 'ER', NULL, FALSE, NOW(), NOW()),
('SZ', 'Eswatini', 'Africa', 'SZL', 'Africa/Mbabane', 'SZ', NULL, FALSE, NOW(), NOW()),
('ET', 'Ethiopia', 'Africa', 'ETB', 'Africa/Addis_Ababa', 'ET', NULL, FALSE, NOW(), NOW()),
('GA', 'Gabon', 'Africa', 'XAF', 'Africa/Libreville', 'GA', NULL, FALSE, NOW(), NOW()),
('GM', 'Gambia', 'Africa', 'GMD', 'Africa/Banjul', 'GM', NULL, FALSE, NOW(), NOW()),
('GH', 'Ghana', 'Africa', 'GHS', 'Africa/Accra', 'GH', NULL, FALSE, NOW(), NOW()),
('GN', 'Guinea', 'Africa', 'GNF', 'Africa/Conakry', 'GN', NULL, FALSE, NOW(), NOW()),
('GW', 'Guinea-Bissau', 'Africa', 'XOF', 'Africa/Bissau', 'GW', NULL, FALSE, NOW(), NOW()),
('KE', 'Kenya', 'Africa', 'KES', 'Africa/Nairobi', 'KE', NULL, FALSE, NOW(), NOW()),
('LS', 'Lesotho', 'Africa', 'LSL', 'Africa/Maseru', 'LS', NULL, FALSE, NOW(), NOW()),
('LR', 'Liberia', 'Africa', 'LRD', 'Africa/Monrovia', 'LR', NULL, FALSE, NOW(), NOW()),
('LY', 'Libya', 'Africa', 'LYD', 'Africa/Tripoli', 'LY', NULL, FALSE, NOW(), NOW()),
('MG', 'Madagascar', 'Africa', 'MGA', 'Indian/Antananarivo', 'MG', NULL, FALSE, NOW(), NOW()),
('MW', 'Malawi', 'Africa', 'MWK', 'Africa/Blantyre', 'MW', NULL, FALSE, NOW(), NOW()),
('ML', 'Mali', 'Africa', 'XOF', 'Africa/Bamako', 'ML', NULL, FALSE, NOW(), NOW()),
('MR', 'Mauritania', 'Africa', 'MRU', 'Africa/Nouakchott', 'MR', NULL, FALSE, NOW(), NOW()),
('MU', 'Mauritius', 'Africa', 'MUR', 'Indian/Mauritius', 'MU', NULL, FALSE, NOW(), NOW()),
('MA', 'Morocco', 'Africa', 'MAD', 'Africa/Casablanca', 'MA', NULL, FALSE, NOW(), NOW()),
('MZ', 'Mozambique', 'Africa', 'MZN', 'Africa/Maputo', 'MZ', NULL, FALSE, NOW(), NOW()),
('NA', 'Namibia', 'Africa', 'NAD', 'Africa/Windhoek', 'NA', NULL, FALSE, NOW(), NOW()),
('NE', 'Niger', 'Africa', 'XOF', 'Africa/Niamey', 'NE', NULL, FALSE, NOW(), NOW()),
('NG', 'Nigeria', 'Africa', 'NGN', 'Africa/Lagos', 'NG', NULL, FALSE, NOW(), NOW()),
('RW', 'Rwanda', 'Africa', 'RWF', 'Africa/Kigali', 'RW', NULL, FALSE, NOW(), NOW()),
('ST', 'Sao Tome and Principe', 'Africa', 'STN', 'Africa/Sao_Tome', 'ST', NULL, FALSE, NOW(), NOW()),
('SN', 'Senegal', 'Africa', 'XOF', 'Africa/Dakar', 'SN', NULL, FALSE, NOW(), NOW()),
('SC', 'Seychelles', 'Africa', 'SCR', 'Indian/Mahe', 'SC', NULL, FALSE, NOW(), NOW()),
('SL', 'Sierra Leone', 'Africa', 'SLL', 'Africa/Freetown', 'SL', NULL, FALSE, NOW(), NOW()),
('SO', 'Somalia', 'Africa', 'SOS', 'Africa/Mogadishu', 'SO', NULL, FALSE, NOW(), NOW()),
('ZA', 'South Africa', 'Africa', 'ZAR', 'Africa/Johannesburg', 'ZA', NULL, FALSE, NOW(), NOW()),
('SS', 'South Sudan', 'Africa', 'SSP', 'Africa/Juba', 'SS', NULL, FALSE, NOW(), NOW()),
('SD', 'Sudan', 'Africa', 'SDG', 'Africa/Khartoum', 'SD', NULL, FALSE, NOW(), NOW()),
('TZ', 'Tanzania', 'Africa', 'TZS', 'Africa/Dar_es_Salaam', 'TZ', NULL, FALSE, NOW(), NOW()),
('TG', 'Togo', 'Africa', 'XOF', 'Africa/Lome', 'TG', NULL, FALSE, NOW(), NOW()),
('TN', 'Tunisia', 'Africa', 'TND', 'Africa/Tunis', 'TN', NULL, FALSE, NOW(), NOW()),
('UG', 'Uganda', 'Africa', 'UGX', 'Africa/Kampala', 'UG', NULL, FALSE, NOW(), NOW()),
('ZM', 'Zambia', 'Africa', 'ZMW', 'Africa/Lusaka', 'ZM', NULL, FALSE, NOW(), NOW()),
('ZW', 'Zimbabwe', 'Africa', 'ZWL', 'Africa/Harare', 'ZW', NULL, FALSE, NOW(), NOW()),
-- Ásia
('AF', 'Afghanistan', 'Asia', 'AFN', 'Asia/Kabul', 'AF', NULL, FALSE, NOW(), NOW()),
('AM', 'Armenia', 'Asia', 'AMD', 'Asia/Yerevan', 'AM', NULL, FALSE, NOW(), NOW()),
('AZ', 'Azerbaijan', 'Asia', 'AZN', 'Asia/Baku', 'AZ', NULL, FALSE, NOW(), NOW()),
('BH', 'Bahrain', 'Asia', 'BHD', 'Asia/Bahrain', 'BH', NULL, FALSE, NOW(), NOW()),
('BD', 'Bangladesh', 'Asia', 'BDT', 'Asia/Dhaka', 'BD', NULL, FALSE, NOW(), NOW()),
('BT', 'Bhutan', 'Asia', 'BTN', 'Asia/Thimphu', 'BT', NULL, FALSE, NOW(), NOW()),
('BN', 'Brunei', 'Asia', 'BND', 'Asia/Brunei', 'BN', NULL, FALSE, NOW(), NOW()),
('KH', 'Cambodia', 'Asia', 'KHR', 'Asia/Phnom_Penh', 'KH', NULL, FALSE, NOW(), NOW()),
('CN', 'China', 'Asia', 'CNY', 'Asia/Shanghai', 'CN', NULL, FALSE, NOW(), NOW()),
('CY', 'Cyprus', 'Asia', 'EUR', 'Asia/Nicosia', 'CY', NULL, FALSE, NOW(), NOW()),
('GE', 'Georgia', 'Asia', 'GEL', 'Asia/Tbilisi', 'GE', NULL, FALSE, NOW(), NOW()),
('IN', 'India', 'Asia', 'INR', 'Asia/Kolkata', 'IN', NULL, FALSE, NOW(), NOW()),
('ID', 'Indonesia', 'Asia', 'IDR', 'Asia/Jakarta', 'ID', NULL, FALSE, NOW(), NOW()),
('IR', 'Iran', 'Asia', 'IRR', 'Asia/Tehran', 'IR', NULL, FALSE, NOW(), NOW()),
('IQ', 'Iraq', 'Asia', 'IQD', 'Asia/Baghdad', 'IQ', NULL, FALSE, NOW(), NOW()),
('IL', 'Israel', 'Asia', 'ILS', 'Asia/Jerusalem', 'IL', NULL, FALSE, NOW(), NOW()),
('JP', 'Japan', 'Asia', 'JPY', 'Asia/Tokyo', 'JP', NULL, FALSE, NOW(), NOW()),
('JO', 'Jordan', 'Asia', 'JOD', 'Asia/Amman', 'JO', NULL, FALSE, NOW(), NOW()),
('KZ', 'Kazakhstan', 'Asia', 'KZT', 'Asia/Almaty', 'KZ', NULL, FALSE, NOW(), NOW()),
('KP', 'North Korea', 'Asia', 'KPW', 'Asia/Pyongyang', 'KP', NULL, FALSE, NOW(), NOW()),
('KR', 'South Korea', 'Asia', 'KRW', 'Asia/Seoul', 'KR', NULL, FALSE, NOW(), NOW()),
('KW', 'Kuwait', 'Asia', 'KWD', 'Asia/Kuwait', 'KW', NULL, FALSE, NOW(), NOW()),
('KG', 'Kyrgyzstan', 'Asia', 'KGS', 'Asia/Bishkek', 'KG', NULL, FALSE, NOW(), NOW()),
('LA', 'Laos', 'Asia', 'LAK', 'Asia/Vientiane', 'LA', NULL, FALSE, NOW(), NOW()),
('LB', 'Lebanon', 'Asia', 'LBP', 'Asia/Beirut', 'LB', NULL, FALSE, NOW(), NOW()),
('MY', 'Malaysia', 'Asia', 'MYR', 'Asia/Kuala_Lumpur', 'MY', NULL, FALSE, NOW(), NOW()),
('MV', 'Maldives', 'Asia', 'MVR', 'Indian/Maldives', 'MV', NULL, FALSE, NOW(), NOW()),
('MN', 'Mongolia', 'Asia', 'MNT', 'Asia/Ulaanbaatar', 'MN', NULL, FALSE, NOW(), NOW()),
('MM', 'Myanmar', 'Asia', 'MMK', 'Asia/Yangon', 'MM', NULL, FALSE, NOW(), NOW()),
('NP', 'Nepal', 'Asia', 'NPR', 'Asia/Kathmandu', 'NP', NULL, FALSE, NOW(), NOW()),
('OM', 'Oman', 'Asia', 'OMR', 'Asia/Muscat', 'OM', NULL, FALSE, NOW(), NOW()),
('PK', 'Pakistan', 'Asia', 'PKR', 'Asia/Karachi', 'PK', NULL, FALSE, NOW(), NOW()),
('PS', 'Palestine', 'Asia', 'ILS', 'Asia/Hebron', 'PS', NULL, FALSE, NOW(), NOW()),
('PH', 'Philippines', 'Asia', 'PHP', 'Asia/Manila', 'PH', NULL, FALSE, NOW(), NOW()),
('QA', 'Qatar', 'Asia', 'QAR', 'Asia/Qatar', 'QA', NULL, FALSE, NOW(), NOW()),
('SA', 'Saudi Arabia', 'Asia', 'SAR', 'Asia/Riyadh', 'SA', NULL, FALSE, NOW(), NOW()),
('SG', 'Singapore', 'Asia', 'SGD', 'Asia/Singapore', 'SG', NULL, FALSE, NOW(), NOW()),
('LK', 'Sri Lanka', 'Asia', 'LKR', 'Asia/Colombo', 'LK', NULL, FALSE, NOW(), NOW()),
('SY', 'Syria', 'Asia', 'SYP', 'Asia/Damascus', 'SY', NULL, FALSE, NOW(), NOW()),
('TW', 'Taiwan', 'Asia', 'TWD', 'Asia/Taipei', 'TW', NULL, FALSE, NOW(), NOW()),
('TJ', 'Tajikistan', 'Asia', 'TJS', 'Asia/Dushanbe', 'TJ', NULL, FALSE, NOW(), NOW()),
('TH', 'Thailand', 'Asia', 'THB', 'Asia/Bangkok', 'TH', NULL, FALSE, NOW(), NOW()),
('TL', 'Timor-Leste', 'Asia', 'USD', 'Asia/Dili', 'TL', NULL, FALSE, NOW(), NOW()),
('TR', 'Turkey', 'Asia', 'TRY', 'Europe/Istanbul', 'TR', NULL, FALSE, NOW(), NOW()),
('TM', 'Turkmenistan', 'Asia', 'TMT', 'Asia/Ashgabat', 'TM', NULL, FALSE, NOW(), NOW()),
('AE', 'United Arab Emirates', 'Asia', 'AED', 'Asia/Dubai', 'AE', NULL, FALSE, NOW(), NOW()),
('UZ', 'Uzbekistan', 'Asia', 'UZS', 'Asia/Tashkent', 'UZ', NULL, FALSE, NOW(), NOW()),
('VN', 'Vietnam', 'Asia', 'VND', 'Asia/Ho_Chi_Minh', 'VN', NULL, FALSE, NOW(), NOW()),
('YE', 'Yemen', 'Asia', 'YER', 'Asia/Aden', 'YE', NULL, FALSE, NOW(), NOW()),
-- Europa
('AL', 'Albania', 'Europe', 'ALL', 'Europe/Tirane', 'AL', NULL, FALSE, NOW(), NOW()),
('AD', 'Andorra', 'Europe', 'EUR', 'Europe/Andorra', 'AD', NULL, FALSE, NOW(), NOW()),
('AT', 'Austria', 'Europe', 'EUR', 'Europe/Vienna', 'AT', NULL, FALSE, NOW(), NOW()),
('BY', 'Belarus', 'Europe', 'BYN', 'Europe/Minsk', 'BY', NULL, FALSE, NOW(), NOW()),
('BE', 'Belgium', 'Europe', 'EUR', 'Europe/Brussels', 'BE', NULL, FALSE, NOW(), NOW()),
('BA', 'Bosnia and Herzegovina', 'Europe', 'BAM', 'Europe/Sarajevo', 'BA', NULL, FALSE, NOW(), NOW()),
('BG', 'Bulgaria', 'Europe', 'BGN', 'Europe/Sofia', 'BG', NULL, FALSE, NOW(), NOW()),
('HR', 'Croatia', 'Europe', 'EUR', 'Europe/Zagreb', 'HR', NULL, FALSE, NOW(), NOW()),
('CZ', 'Czech Republic', 'Europe', 'CZK', 'Europe/Prague', 'CZ', NULL, FALSE, NOW(), NOW()),
('DK', 'Denmark', 'Europe', 'DKK', 'Europe/Copenhagen', 'DK', NULL, FALSE, NOW(), NOW()),
('EE', 'Estonia', 'Europe', 'EUR', 'Europe/Tallinn', 'EE', NULL, FALSE, NOW(), NOW()),
('FI', 'Finland', 'Europe', 'EUR', 'Europe/Helsinki', 'FI', NULL, FALSE, NOW(), NOW()),
('FR', 'France', 'Europe', 'EUR', 'Europe/Paris', 'FR', NULL, FALSE, NOW(), NOW()),
('DE', 'Germany', 'Europe', 'EUR', 'Europe/Berlin', 'DE', NULL, FALSE, NOW(), NOW()),
('GR', 'Greece', 'Europe', 'EUR', 'Europe/Athens', 'GR', NULL, FALSE, NOW(), NOW()),
('HU', 'Hungary', 'Europe', 'HUF', 'Europe/Budapest', 'HU', NULL, FALSE, NOW(), NOW()),
('IS', 'Iceland', 'Europe', 'ISK', 'Atlantic/Reykjavik', 'IS', NULL, FALSE, NOW(), NOW()),
('IE', 'Ireland', 'Europe', 'EUR', 'Europe/Dublin', 'IE', NULL, FALSE, NOW(), NOW()),
('IT', 'Italy', 'Europe', 'EUR', 'Europe/Rome', 'IT', NULL, FALSE, NOW(), NOW()),
('LV', 'Latvia', 'Europe', 'EUR', 'Europe/Riga', 'LV', NULL, FALSE, NOW(), NOW()),
('LI', 'Liechtenstein', 'Europe', 'CHF', 'Europe/Vaduz', 'LI', NULL, FALSE, NOW(), NOW()),
('LT', 'Lithuania', 'Europe', 'EUR', 'Europe/Vilnius', 'LT', NULL, FALSE, NOW(), NOW()),
('LU', 'Luxembourg', 'Europe', 'EUR', 'Europe/Luxembourg', 'LU', NULL, FALSE, NOW(), NOW()),
('MT', 'Malta', 'Europe', 'EUR', 'Europe/Malta', 'MT', NULL, FALSE, NOW(), NOW()),
('MD', 'Moldova', 'Europe', 'MDL', 'Europe/Chisinau', 'MD', NULL, FALSE, NOW(), NOW()),
('MC', 'Monaco', 'Europe', 'EUR', 'Europe/Monaco', 'MC', NULL, FALSE, NOW(), NOW()),
('ME', 'Montenegro', 'Europe', 'EUR', 'Europe/Podgorica', 'ME', NULL, FALSE, NOW(), NOW()),
('NL', 'Netherlands', 'Europe', 'EUR', 'Europe/Amsterdam', 'NL', NULL, FALSE, NOW(), NOW()),
('MK', 'North Macedonia', 'Europe', 'MKD', 'Europe/Skopje', 'MK', NULL, FALSE, NOW(), NOW()),
('NO', 'Norway', 'Europe', 'NOK', 'Europe/Oslo', 'NO', NULL, FALSE, NOW(), NOW()),
('PL', 'Poland', 'Europe', 'PLN', 'Europe/Warsaw', 'PL', NULL, FALSE, NOW(), NOW()),
('RO', 'Romania', 'Europe', 'RON', 'Europe/Bucharest', 'RO', NULL, FALSE, NOW(), NOW()),
('RU', 'Russia', 'Europe', 'RUB', 'Europe/Moscow', 'RU', NULL, FALSE, NOW(), NOW()),
('SM', 'San Marino', 'Europe', 'EUR', 'Europe/San_Marino', 'SM', NULL, FALSE, NOW(), NOW()),
('RS', 'Serbia', 'Europe', 'RSD', 'Europe/Belgrade', 'RS', NULL, FALSE, NOW(), NOW()),
('SK', 'Slovakia', 'Europe', 'EUR', 'Europe/Bratislava', 'SK', NULL, FALSE, NOW(), NOW()),
('SI', 'Slovenia', 'Europe', 'EUR', 'Europe/Ljubljana', 'SI', NULL, FALSE, NOW(), NOW()),
('SE', 'Sweden', 'Europe', 'SEK', 'Europe/Stockholm', 'SE', NULL, FALSE, NOW(), NOW()),
('CH', 'Switzerland', 'Europe', 'CHF', 'Europe/Zurich', 'CH', NULL, FALSE, NOW(), NOW()),
('UA', 'Ukraine', 'Europe', 'UAH', 'Europe/Kiev', 'UA', NULL, FALSE, NOW(), NOW()),
('GB', 'United Kingdom', 'Europe', 'GBP', 'Europe/London', 'GB', NULL, FALSE, NOW(), NOW()),
('VA', 'Vatican City', 'Europe', 'EUR', 'Europe/Vatican', 'VA', NULL, FALSE, NOW(), NOW()),
-- América do Norte
('AG', 'Antigua and Barbuda', 'North America', 'XCD', 'America/Antigua', 'AG', NULL, FALSE, NOW(), NOW()),
('BS', 'Bahamas', 'North America', 'BSD', 'America/Nassau', 'BS', NULL, FALSE, NOW(), NOW()),
('BB', 'Barbados', 'North America', 'BBD', 'America/Barbados', 'BB', NULL, FALSE, NOW(), NOW()),
('BZ', 'Belize', 'North America', 'BZD', 'America/Belize', 'BZ', NULL, FALSE, NOW(), NOW()),
('CA', 'Canada', 'North America', 'CAD', 'America/Toronto', 'CA', NULL, FALSE, NOW(), NOW()),
('CR', 'Costa Rica', 'North America', 'CRC', 'America/Costa_Rica', 'CR', NULL, FALSE, NOW(), NOW()),
('CU', 'Cuba', 'North America', 'CUP', 'America/Havana', 'CU', NULL, FALSE, NOW(), NOW()),
('DM', 'Dominica', 'North America', 'XCD', 'America/Dominica', 'DM', NULL, FALSE, NOW(), NOW()),
('DO', 'Dominican Republic', 'North America', 'DOP', 'America/Santo_Domingo', 'DO', NULL, FALSE, NOW(), NOW()),
('SV', 'El Salvador', 'North America', 'USD', 'America/El_Salvador', 'SV', NULL, FALSE, NOW(), NOW()),
('GD', 'Grenada', 'North America', 'XCD', 'America/Grenada', 'GD', NULL, FALSE, NOW(), NOW()),
('GT', 'Guatemala', 'North America', 'GTQ', 'America/Guatemala', 'GT', NULL, FALSE, NOW(), NOW()),
('HT', 'Haiti', 'North America', 'HTG', 'America/Port-au-Prince', 'HT', NULL, FALSE, NOW(), NOW()),
('HN', 'Honduras', 'North America', 'HNL', 'America/Tegucigalpa', 'HN', NULL, FALSE, NOW(), NOW()),
('JM', 'Jamaica', 'North America', 'JMD', 'America/Jamaica', 'JM', NULL, FALSE, NOW(), NOW()),
('MX', 'Mexico', 'North America', 'MXN', 'America/Mexico_City', 'MX', NULL, FALSE, NOW(), NOW()),
('NI', 'Nicaragua', 'North America', 'NIO', 'America/Managua', 'NI', NULL, FALSE, NOW(), NOW()),
('PA', 'Panama', 'North America', 'PAB', 'America/Panama', 'PA', NULL, FALSE, NOW(), NOW()),
('KN', 'Saint Kitts and Nevis', 'North America', 'XCD', 'America/St_Kitts', 'KN', NULL, FALSE, NOW(), NOW()),
('LC', 'Saint Lucia', 'North America', 'XCD', 'America/St_Lucia', 'LC', NULL, FALSE, NOW(), NOW()),
('VC', 'Saint Vincent and the Grenadines', 'North America', 'XCD', 'America/St_Vincent', 'VC', NULL, FALSE, NOW(), NOW()),
('TT', 'Trinidad and Tobago', 'North America', 'TTD', 'America/Port_of_Spain', 'TT', NULL, FALSE, NOW(), NOW()),
('US', 'United States', 'North America', 'USD', 'America/New_York', 'US', NULL, FALSE, NOW(), NOW()),
-- América do Sul
('AR', 'Argentina', 'South America', 'ARS', 'America/Argentina/Buenos_Aires', 'AR', NULL, FALSE, NOW(), NOW()),
('BO', 'Bolivia', 'South America', 'BOB', 'America/La_Paz', 'BO', NULL, FALSE, NOW(), NOW()),
('CL', 'Chile', 'South America', 'CLP', 'America/Santiago', 'CL', NULL, FALSE, NOW(), NOW()),
('CO', 'Colombia', 'South America', 'COP', 'America/Bogota', 'CO', NULL, FALSE, NOW(), NOW()),
('EC', 'Ecuador', 'South America', 'USD', 'America/Guayaquil', 'EC', NULL, FALSE, NOW(), NOW()),
('GY', 'Guyana', 'South America', 'GYD', 'America/Guyana', 'GY', NULL, FALSE, NOW(), NOW()),
('PY', 'Paraguay', 'South America', 'PYG', 'America/Asuncion', 'PY', NULL, FALSE, NOW(), NOW()),
('PE', 'Peru', 'South America', 'PEN', 'America/Lima', 'PE', NULL, FALSE, NOW(), NOW()),
('SR', 'Suriname', 'South America', 'SRD', 'America/Paramaribo', 'SR', NULL, FALSE, NOW(), NOW()),
('UY', 'Uruguay', 'South America', 'UYU', 'America/Montevideo', 'UY', NULL, FALSE, NOW(), NOW()),
('VE', 'Venezuela', 'South America', 'VES', 'America/Caracas', 'VE', NULL, FALSE, NOW(), NOW()),
-- Oceania
('AU', 'Australia', 'Oceania', 'AUD', 'Australia/Sydney', 'AU', NULL, FALSE, NOW(), NOW()),
('FJ', 'Fiji', 'Oceania', 'FJD', 'Pacific/Fiji', 'FJ', NULL, FALSE, NOW(), NOW()),
('KI', 'Kiribati', 'Oceania', 'AUD', 'Pacific/Tarawa', 'KI', NULL, FALSE, NOW(), NOW()),
('MH', 'Marshall Islands', 'Oceania', 'USD', 'Pacific/Majuro', 'MH', NULL, FALSE, NOW(), NOW()),
('FM', 'Micronesia', 'Oceania', 'USD', 'Pacific/Chuuk', 'FM', NULL, FALSE, NOW(), NOW()),
('NR', 'Nauru', 'Oceania', 'AUD', 'Pacific/Nauru', 'NR', NULL, FALSE, NOW(), NOW()),
('NZ', 'New Zealand', 'Oceania', 'NZD', 'Pacific/Auckland', 'NZ', NULL, FALSE, NOW(), NOW()),
('PW', 'Palau', 'Oceania', 'USD', 'Pacific/Palau', 'PW', NULL, FALSE, NOW(), NOW()),
('PG', 'Papua New Guinea', 'Oceania', 'PGK', 'Pacific/Port_Moresby', 'PG', NULL, FALSE, NOW(), NOW()),
('WS', 'Samoa', 'Oceania', 'WST', 'Pacific/Apia', 'WS', NULL, FALSE, NOW(), NOW()),
('SB', 'Solomon Islands', 'Oceania', 'SBD', 'Pacific/Guadalcanal', 'SB', NULL, FALSE, NOW(), NOW()),
('TO', 'Tonga', 'Oceania', 'TOP', 'Pacific/Tongatapu', 'TO', NULL, FALSE, NOW(), NOW()),
('TV', 'Tuvalu', 'Oceania', 'AUD', 'Pacific/Funafuti', 'TV', NULL, FALSE, NOW(), NOW()),
('VU', 'Vanuatu', 'Oceania', 'VUV', 'Pacific/Efate', 'VU', NULL, FALSE, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;

COMMIT;