SELECT enum_range(NULL::paymentstatus);

-- resultado 
-- enum_range
-- {CREATED,PENDING_CUSTOMER_ACTION,PENDING_PROVIDER_CONFIRMATION,
-- APPROVED,DECLINED,EXPIRED,FAILED,CANCELLED,AWAITING_INTEGRATION}
