-- HOTFIX: Inserção de províncias/estados (com escape correto para apóstrofos)

INSERT INTO public.capability_province (code, name, country_code, province_code_original, region, timezone, is_active, metadata_json, created_at, updated_at) VALUES

-- BRASIL (completando os faltantes)
('BR-AC', 'Acre', 'BR', 'AC', 'Norte', 'America/Rio_Branco', True, NULL, NOW(), NOW()),
('BR-AL', 'Alagoas', 'BR', 'AL', 'Nordeste', 'America/Maceio', True, NULL, NOW(), NOW()),
('BR-AP', 'Amapá', 'BR', 'AP', 'Norte', 'America/Belem', True, NULL, NOW(), NOW()),
('BR-AM', 'Amazonas', 'BR', 'AM', 'Norte', 'America/Manaus', True, NULL, NOW(), NOW()),
('BR-CE', 'Ceará', 'BR', 'CE', 'Nordeste', 'America/Fortaleza', True, NULL, NOW(), NOW()),
('BR-ES', 'Espírito Santo', 'BR', 'ES', 'Sudeste', 'America/Sao_Paulo', True, NULL, NOW(), NOW()),
('BR-GO', 'Goiás', 'BR', 'GO', 'Centro-Oeste', 'America/Sao_Paulo', True, NULL, NOW(), NOW()),
('BR-MA', 'Maranhão', 'BR', 'MA', 'Nordeste', 'America/Fortaleza', True, NULL, NOW(), NOW()),
('BR-MT', 'Mato Grosso', 'BR', 'MT', 'Centro-Oeste', 'America/Cuiaba', True, NULL, NOW(), NOW()),
('BR-MS', 'Mato Grosso do Sul', 'BR', 'MS', 'Centro-Oeste', 'America/Campo_Grande', True, NULL, NOW(), NOW()),
('BR-PA', 'Pará', 'BR', 'PA', 'Norte', 'America/Belem', True, NULL, NOW(), NOW()),
('BR-PB', 'Paraíba', 'BR', 'PB', 'Nordeste', 'America/Fortaleza', True, NULL, NOW(), NOW()),
('BR-PI', 'Piauí', 'BR', 'PI', 'Nordeste', 'America/Fortaleza', True, NULL, NOW(), NOW()),
('BR-RN', 'Rio Grande do Norte', 'BR', 'RN', 'Nordeste', 'America/Fortaleza', True, NULL, NOW(), NOW()),
('BR-RO', 'Rondônia', 'BR', 'RO', 'Norte', 'America/Porto_Velho', True, NULL, NOW(), NOW()),
('BR-RR', 'Roraima', 'BR', 'RR', 'Norte', 'America/Boa_Vista', True, NULL, NOW(), NOW()),
('BR-SC', 'Santa Catarina', 'BR', 'SC', 'Sul', 'America/Sao_Paulo', True, NULL, NOW(), NOW()),
('BR-SE', 'Sergipe', 'BR', 'SE', 'Nordeste', 'America/Maceio', True, NULL, NOW(), NOW()),
('BR-TO', 'Tocantins', 'BR', 'TO', 'Norte', 'America/Araguaina', True, NULL, NOW(), NOW()),

-- PORTUGAL
('PT-01', 'Aveiro', 'PT', '01', 'Centro', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-02', 'Beja', 'PT', '02', 'Alentejo', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
-- ('PT-03', 'Braga', 'PT', '03', 'Norte', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-04', 'Bragança', 'PT', '04', 'Norte', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-05', 'Castelo Branco', 'PT', '05', 'Centro', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-06', 'Coimbra', 'PT', '06', 'Centro', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-07', 'Évora', 'PT', '07', 'Alentejo', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-08', 'Faro', 'PT', '08', 'Algarve', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-09', 'Guarda', 'PT', '09', 'Centro', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-10', 'Leiria', 'PT', '10', 'Centro', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
-- ('PT-11', 'Lisboa', 'PT', '11', 'Lisboa', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-12', 'Portalegre', 'PT', '12', 'Alentejo', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
-- ('PT-13', 'Porto', 'PT', '13', 'Norte', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-14', 'Santarém', 'PT', '14', 'Centro', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-15', 'Setúbal', 'PT', '15', 'Lisboa', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-16', 'Viana do Castelo', 'PT', '16', 'Norte', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-17', 'Vila Real', 'PT', '17', 'Norte', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-18', 'Viseu', 'PT', '18', 'Centro', 'Europe/Lisbon', True, NULL, NOW(), NOW()),
('PT-20', 'Açores', 'PT', '20', 'Açores', 'Atlantic/Azores', True, NULL, NOW(), NOW()),
('PT-30', 'Madeira', 'PT', '30', 'Madeira', 'Atlantic/Madeira', True, NULL, NOW(), NOW()),

-- ESPANHA
('ES-C', 'A Coruña', 'ES', 'C', 'Galicia', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-VI', 'Álava', 'ES', 'VI', 'País Vasco', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-AB', 'Albacete', 'ES', 'AB', 'Castilla-La Mancha', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-A', 'Alicante', 'ES', 'A', 'Comunidad Valenciana', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-AL', 'Almería', 'ES', 'AL', 'Andalucía', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-O', 'Asturias', 'ES', 'O', 'Asturias', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-AV', 'Ávila', 'ES', 'AV', 'Castilla y León', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-BA', 'Badajoz', 'ES', 'BA', 'Extremadura', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-PM', 'Baleares', 'ES', 'PM', 'Islas Baleares', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-B', 'Barcelona', 'ES', 'B', 'Cataluña', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-BU', 'Burgos', 'ES', 'BU', 'Castilla y León', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-CC', 'Cáceres', 'ES', 'CC', 'Extremadura', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-CA', 'Cádiz', 'ES', 'CA', 'Andalucía', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-S', 'Cantabria', 'ES', 'S', 'Cantabria', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-CS', 'Castellón', 'ES', 'CS', 'Comunidad Valenciana', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-CR', 'Ciudad Real', 'ES', 'CR', 'Castilla-La Mancha', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-CO', 'Córdoba', 'ES', 'CO', 'Andalucía', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-CU', 'Cuenca', 'ES', 'CU', 'Castilla-La Mancha', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-GI', 'Girona', 'ES', 'GI', 'Cataluña', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-GR', 'Granada', 'ES', 'GR', 'Andalucía', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-GU', 'Guadalajara', 'ES', 'GU', 'Castilla-La Mancha', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-SS', 'Guipúzcoa', 'ES', 'SS', 'País Vasco', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-H', 'Huelva', 'ES', 'H', 'Andalucía', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-HU', 'Huesca', 'ES', 'HU', 'Aragón', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-J', 'Jaén', 'ES', 'J', 'Andalucía', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-LO', 'La Rioja', 'ES', 'LO', 'La Rioja', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-GC', 'Las Palmas', 'ES', 'GC', 'Canarias', 'Atlantic/Canary', True, NULL, NOW(), NOW()),
('ES-LE', 'León', 'ES', 'LE', 'Castilla y León', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-L', 'Lleida', 'ES', 'L', 'Cataluña', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-LU', 'Lugo', 'ES', 'LU', 'Galicia', 'Europe/Madrid', True, NULL, NOW(), NOW()),
-- ('ES-M', 'Madrid', 'ES', 'M', 'Comunidad de Madrid', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-MA', 'Málaga', 'ES', 'MA', 'Andalucía', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-MU', 'Murcia', 'ES', 'MU', 'Murcia', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-NA', 'Navarra', 'ES', 'NA', 'Navarra', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-OR', 'Ourense', 'ES', 'OR', 'Galicia', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-P', 'Palencia', 'ES', 'P', 'Castilla y León', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-PO', 'Pontevedra', 'ES', 'PO', 'Galicia', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-SA', 'Salamanca', 'ES', 'SA', 'Castilla y León', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-TF', 'Santa Cruz de Tenerife', 'ES', 'TF', 'Canarias', 'Atlantic/Canary', True, NULL, NOW(), NOW()),
('ES-SG', 'Segovia', 'ES', 'SG', 'Castilla y León', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-SE', 'Sevilla', 'ES', 'SE', 'Andalucía', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-SO', 'Soria', 'ES', 'SO', 'Castilla y León', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-T', 'Tarragona', 'ES', 'T', 'Cataluña', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-TE', 'Teruel', 'ES', 'TE', 'Aragón', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-TO', 'Toledo', 'ES', 'TO', 'Castilla-La Mancha', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-V', 'Valencia', 'ES', 'V', 'Comunidad Valenciana', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-VA', 'Valladolid', 'ES', 'VA', 'Castilla y León', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-BI', 'Vizcaya', 'ES', 'BI', 'País Vasco', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-ZA', 'Zamora', 'ES', 'ZA', 'Castilla y León', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-Z', 'Zaragoza', 'ES', 'Z', 'Aragón', 'Europe/Madrid', True, NULL, NOW(), NOW()),
('ES-CE', 'Ceuta', 'ES', 'CE', 'Ceuta', 'Africa/Ceuta', True, NULL, NOW(), NOW()),
('ES-ML', 'Melilla', 'ES', 'ML', 'Melilla', 'Africa/Ceuta', True, NULL, NOW(), NOW()),

-- ARGENTINA
('AR-B', 'Buenos Aires', 'AR', 'B', 'Pampas', 'America/Argentina/Buenos_Aires', True, NULL, NOW(), NOW()),
('AR-C', 'CABA', 'AR', 'C', 'Pampas', 'America/Argentina/Buenos_Aires', True, NULL, NOW(), NOW()),
('AR-K', 'Catamarca', 'AR', 'K', 'Noroeste', 'America/Argentina/Catamarca', True, NULL, NOW(), NOW()),
('AR-H', 'Chaco', 'AR', 'H', 'Noreste', 'America/Argentina/Cordoba', True, NULL, NOW(), NOW()),
('AR-U', 'Chubut', 'AR', 'U', 'Patagonia', 'America/Argentina/Salta', True, NULL, NOW(), NOW()),
('AR-X', 'Córdoba', 'AR', 'X', 'Pampas', 'America/Argentina/Cordoba', True, NULL, NOW(), NOW()),
('AR-W', 'Corrientes', 'AR', 'W', 'Noreste', 'America/Argentina/Cordoba', True, NULL, NOW(), NOW()),
('AR-E', 'Entre Ríos', 'AR', 'E', 'Pampas', 'America/Argentina/Cordoba', True, NULL, NOW(), NOW()),
('AR-P', 'Formosa', 'AR', 'P', 'Noreste', 'America/Argentina/Cordoba', True, NULL, NOW(), NOW()),
('AR-Y', 'Jujuy', 'AR', 'Y', 'Noroeste', 'America/Argentina/Jujuy', True, NULL, NOW(), NOW()),
('AR-L', 'La Pampa', 'AR', 'L', 'Pampas', 'America/Argentina/Salta', True, NULL, NOW(), NOW()),
('AR-F', 'La Rioja', 'AR', 'F', 'Noroeste', 'America/Argentina/La_Rioja', True, NULL, NOW(), NOW()),
('AR-M', 'Mendoza', 'AR', 'M', 'Cuyo', 'America/Argentina/Mendoza', True, NULL, NOW(), NOW()),
('AR-N', 'Misiones', 'AR', 'N', 'Noreste', 'America/Argentina/Cordoba', True, NULL, NOW(), NOW()),
('AR-Q', 'Neuquén', 'AR', 'Q', 'Patagonia', 'America/Argentina/Salta', True, NULL, NOW(), NOW()),
('AR-R', 'Río Negro', 'AR', 'R', 'Patagonia', 'America/Argentina/Salta', True, NULL, NOW(), NOW()),
('AR-A', 'Salta', 'AR', 'A', 'Noroeste', 'America/Argentina/Salta', True, NULL, NOW(), NOW()),
('AR-J', 'San Juan', 'AR', 'J', 'Cuyo', 'America/Argentina/San_Juan', True, NULL, NOW(), NOW()),
('AR-D', 'San Luis', 'AR', 'D', 'Cuyo', 'America/Argentina/San_Luis', True, NULL, NOW(), NOW()),
('AR-Z', 'Santa Cruz', 'AR', 'Z', 'Patagonia', 'America/Argentina/Rio_Gallegos', True, NULL, NOW(), NOW()),
('AR-S', 'Santa Fe', 'AR', 'S', 'Pampas', 'America/Argentina/Cordoba', True, NULL, NOW(), NOW()),
('AR-G', 'Santiago del Estero', 'AR', 'G', 'Noroeste', 'America/Argentina/Cordoba', True, NULL, NOW(), NOW()),
('AR-V', 'Tierra del Fuego', 'AR', 'V', 'Patagonia', 'America/Argentina/Ushuaia', True, NULL, NOW(), NOW()),
('AR-T', 'Tucumán', 'AR', 'T', 'Noroeste', 'America/Argentina/Tucuman', True, NULL, NOW(), NOW()),

-- MÉXICO
('MX-AG', 'Aguascalientes', 'MX', 'AG', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-BC', 'Baja California', 'MX', 'BC', 'Noroeste', 'America/Tijuana', True, NULL, NOW(), NOW()),
('MX-BS', 'Baja California Sur', 'MX', 'BS', 'Noroeste', 'America/Mazatlan', True, NULL, NOW(), NOW()),
('MX-CM', 'Campeche', 'MX', 'CM', 'Sureste', 'America/Merida', True, NULL, NOW(), NOW()),
('MX-CS', 'Chiapas', 'MX', 'CS', 'Sureste', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-CH', 'Chihuahua', 'MX', 'CH', 'Norte', 'America/Chihuahua', True, NULL, NOW(), NOW()),
('MX-CX', 'Ciudad de México', 'MX', 'CX', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-CO', 'Coahuila', 'MX', 'CO', 'Norte', 'America/Monterrey', True, NULL, NOW(), NOW()),
('MX-CL', 'Colima', 'MX', 'CL', 'Pacífico', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-DG', 'Durango', 'MX', 'DG', 'Norte', 'America/Monterrey', True, NULL, NOW(), NOW()),
('MX-GT', 'Guanajuato', 'MX', 'GT', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-GR', 'Guerrero', 'MX', 'GR', 'Pacífico', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-HG', 'Hidalgo', 'MX', 'HG', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-JA', 'Jalisco', 'MX', 'JA', 'Pacífico', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-MX', 'Estado de México', 'MX', 'MX', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-MI', 'Michoacán', 'MX', 'MI', 'Pacífico', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-MO', 'Morelos', 'MX', 'MO', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-NA', 'Nayarit', 'MX', 'NA', 'Pacífico', 'America/Mazatlan', True, NULL, NOW(), NOW()),
('MX-NL', 'Nuevo León', 'MX', 'NL', 'Norte', 'America/Monterrey', True, NULL, NOW(), NOW()),
('MX-OA', 'Oaxaca', 'MX', 'OA', 'Sureste', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-PU', 'Puebla', 'MX', 'PU', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-QT', 'Querétaro', 'MX', 'QT', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-QR', 'Quintana Roo', 'MX', 'QR', 'Sureste', 'America/Cancun', True, NULL, NOW(), NOW()),
('MX-SL', 'San Luis Potosí', 'MX', 'SL', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-SI', 'Sinaloa', 'MX', 'SI', 'Noroeste', 'America/Mazatlan', True, NULL, NOW(), NOW()),
('MX-SO', 'Sonora', 'MX', 'SO', 'Noroeste', 'America/Hermosillo', True, NULL, NOW(), NOW()),
('MX-TB', 'Tabasco', 'MX', 'TB', 'Sureste', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-TM', 'Tamaulipas', 'MX', 'TM', 'Noreste', 'America/Monterrey', True, NULL, NOW(), NOW()),
('MX-TL', 'Tlaxcala', 'MX', 'TL', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-VE', 'Veracruz', 'MX', 'VE', 'Sureste', 'America/Mexico_City', True, NULL, NOW(), NOW()),
('MX-YU', 'Yucatán', 'MX', 'YU', 'Sureste', 'America/Merida', True, NULL, NOW(), NOW()),
('MX-ZA', 'Zacatecas', 'MX', 'ZA', 'Centro', 'America/Mexico_City', True, NULL, NOW(), NOW()),

-- COLÔMBIA
('CO-AM', 'Amazonas', 'CO', 'AM', 'Amazonía', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-AN', 'Antioquia', 'CO', 'AN', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-AR', 'Arauca', 'CO', 'AR', 'Orinoquía', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-AT', 'Atlántico', 'CO', 'AT', 'Caribe', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-BL', 'Bolívar', 'CO', 'BL', 'Caribe', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-BY', 'Boyacá', 'CO', 'BY', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-CL', 'Caldas', 'CO', 'CL', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-CQ', 'Caquetá', 'CO', 'CQ', 'Amazonía', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-CS', 'Casanare', 'CO', 'CS', 'Orinoquía', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-CA', 'Cauca', 'CO', 'CA', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-CE', 'Cesar', 'CO', 'CE', 'Caribe', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-CH', 'Chocó', 'CO', 'CH', 'Pacífica', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-CR', 'Córdoba', 'CO', 'CR', 'Caribe', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-CU', 'Cundinamarca', 'CO', 'CU', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-DC', 'Bogotá D.C.', 'CO', 'DC', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-GN', 'Guainía', 'CO', 'GN', 'Amazonía', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-GV', 'Guaviare', 'CO', 'GV', 'Amazonía', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-HU', 'Huila', 'CO', 'HU', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-LG', 'La Guajira', 'CO', 'LG', 'Caribe', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-MG', 'Magdalena', 'CO', 'MG', 'Caribe', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-MT', 'Meta', 'CO', 'MT', 'Orinoquía', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-NA', 'Nariño', 'CO', 'NA', 'Pacífica', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-NS', 'Norte de Santander', 'CO', 'NS', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-PU', 'Putumayo', 'CO', 'PU', 'Amazonía', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-QD', 'Quindío', 'CO', 'QD', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-RI', 'Risaralda', 'CO', 'RI', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-SA', 'San Andrés', 'CO', 'SA', 'Caribe', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-ST', 'Santander', 'CO', 'ST', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-SU', 'Sucre', 'CO', 'SU', 'Caribe', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-TO', 'Tolima', 'CO', 'TO', 'Andina', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-VC', 'Valle del Cauca', 'CO', 'VC', 'Pacífica', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-VA', 'Vaupés', 'CO', 'VA', 'Amazonía', 'America/Bogota', True, NULL, NOW(), NOW()),
('CO-VD', 'Vichada', 'CO', 'VD', 'Orinoquía', 'America/Bogota', True, NULL, NOW(), NOW()),

-- FRANÇA (com escape correto usando '' duas aspas simples)
('FR-01', 'Ain', 'FR', '01', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-02', 'Aisne', 'FR', '02', 'Hauts-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-03', 'Allier', 'FR', '03', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-04', 'Alpes-de-Haute-Provence', 'FR', '04', 'Provence-Alpes-Côte d''Azur', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-05', 'Hautes-Alpes', 'FR', '05', 'Provence-Alpes-Côte d''Azur', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-06', 'Alpes-Maritimes', 'FR', '06', 'Provence-Alpes-Côte d''Azur', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-07', 'Ardèche', 'FR', '07', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-08', 'Ardennes', 'FR', '08', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-09', 'Ariège', 'FR', '09', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-10', 'Aube', 'FR', '10', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-11', 'Aude', 'FR', '11', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-12', 'Aveyron', 'FR', '12', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-13', 'Bouches-du-Rhône', 'FR', '13', 'Provence-Alpes-Côte d''Azur', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-14', 'Calvados', 'FR', '14', 'Normandie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-15', 'Cantal', 'FR', '15', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-16', 'Charente', 'FR', '16', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-17', 'Charente-Maritime', 'FR', '17', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-18', 'Cher', 'FR', '18', 'Centre-Val de Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-19', 'Corrèze', 'FR', '19', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-2A', 'Corse-du-Sud', 'FR', '2A', 'Corse', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-2B', 'Haute-Corse', 'FR', '2B', 'Corse', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-21', 'Côte-d''Or', 'FR', '21', 'Bourgogne-Franche-Comté', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-22', 'Côtes-d''Armor', 'FR', '22', 'Bretagne', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-23', 'Creuse', 'FR', '23', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-24', 'Dordogne', 'FR', '24', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-25', 'Doubs', 'FR', '25', 'Bourgogne-Franche-Comté', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-26', 'Drôme', 'FR', '26', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-27', 'Eure', 'FR', '27', 'Normandie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-28', 'Eure-et-Loir', 'FR', '28', 'Centre-Val de Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-29', 'Finistère', 'FR', '29', 'Bretagne', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-30', 'Gard', 'FR', '30', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-31', 'Haute-Garonne', 'FR', '31', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-32', 'Gers', 'FR', '32', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-33', 'Gironde', 'FR', '33', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-34', 'Hérault', 'FR', '34', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-35', 'Ille-et-Vilaine', 'FR', '35', 'Bretagne', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-36', 'Indre', 'FR', '36', 'Centre-Val de Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-37', 'Indre-et-Loire', 'FR', '37', 'Centre-Val de Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-38', 'Isère', 'FR', '38', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-39', 'Jura', 'FR', '39', 'Bourgogne-Franche-Comté', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-40', 'Landes', 'FR', '40', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-41', 'Loir-et-Cher', 'FR', '41', 'Centre-Val de Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-42', 'Loire', 'FR', '42', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-43', 'Haute-Loire', 'FR', '43', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-44', 'Loire-Atlantique', 'FR', '44', 'Pays de la Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-45', 'Loiret', 'FR', '45', 'Centre-Val de Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-46', 'Lot', 'FR', '46', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-47', 'Lot-et-Garonne', 'FR', '47', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-48', 'Lozère', 'FR', '48', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-49', 'Maine-et-Loire', 'FR', '49', 'Pays de la Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-50', 'Manche', 'FR', '50', 'Normandie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-51', 'Marne', 'FR', '51', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-52', 'Haute-Marne', 'FR', '52', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-53', 'Mayenne', 'FR', '53', 'Pays de la Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-54', 'Meurthe-et-Moselle', 'FR', '54', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-55', 'Meuse', 'FR', '55', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-56', 'Morbihan', 'FR', '56', 'Bretagne', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-57', 'Moselle', 'FR', '57', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-58', 'Nièvre', 'FR', '58', 'Bourgogne-Franche-Comté', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-59', 'Nord', 'FR', '59', 'Hauts-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-60', 'Oise', 'FR', '60', 'Hauts-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-61', 'Orne', 'FR', '61', 'Normandie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-62', 'Pas-de-Calais', 'FR', '62', 'Hauts-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-63', 'Puy-de-Dôme', 'FR', '63', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-64', 'Pyrénées-Atlantiques', 'FR', '64', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-65', 'Hautes-Pyrénées', 'FR', '65', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-66', 'Pyrénées-Orientales', 'FR', '66', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-67', 'Bas-Rhin', 'FR', '67', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-68', 'Haut-Rhin', 'FR', '68', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-69', 'Rhône', 'FR', '69', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-70', 'Haute-Saône', 'FR', '70', 'Bourgogne-Franche-Comté', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-71', 'Saône-et-Loire', 'FR', '71', 'Bourgogne-Franche-Comté', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-72', 'Sarthe', 'FR', '72', 'Pays de la Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-73', 'Savoie', 'FR', '73', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-74', 'Haute-Savoie', 'FR', '74', 'Auvergne-Rhône-Alpes', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-75', 'Paris', 'FR', '75', 'Île-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-76', 'Seine-Maritime', 'FR', '76', 'Normandie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-77', 'Seine-et-Marne', 'FR', '77', 'Île-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-78', 'Yvelines', 'FR', '78', 'Île-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-79', 'Deux-Sèvres', 'FR', '79', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-80', 'Somme', 'FR', '80', 'Hauts-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-81', 'Tarn', 'FR', '81', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-82', 'Tarn-et-Garonne', 'FR', '82', 'Occitanie', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-83', 'Var', 'FR', '83', 'Provence-Alpes-Côte d''Azur', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-84', 'Vaucluse', 'FR', '84', 'Provence-Alpes-Côte d''Azur', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-85', 'Vendée', 'FR', '85', 'Pays de la Loire', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-86', 'Vienne', 'FR', '86', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-87', 'Haute-Vienne', 'FR', '87', 'Nouvelle-Aquitaine', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-88', 'Vosges', 'FR', '88', 'Grand Est', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-89', 'Yonne', 'FR', '89', 'Bourgogne-Franche-Comté', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-90', 'Territoire de Belfort', 'FR', '90', 'Bourgogne-Franche-Comté', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-91', 'Essonne', 'FR', '91', 'Île-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-92', 'Hauts-de-Seine', 'FR', '92', 'Île-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-93', 'Seine-Saint-Denis', 'FR', '93', 'Île-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-94', 'Val-de-Marne', 'FR', '94', 'Île-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),
('FR-95', 'Val-d''Oise', 'FR', '95', 'Île-de-France', 'Europe/Paris', True, NULL, NOW(), NOW()),

-- ESTADOS UNIDOS
('US-AL', 'Alabama', 'US', 'AL', 'Southeast', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-AK', 'Alaska', 'US', 'AK', 'Pacific', 'America/Anchorage', True, NULL, NOW(), NOW()),
('US-AZ', 'Arizona', 'US', 'AZ', 'Southwest', 'America/Phoenix', True, NULL, NOW(), NOW()),
('US-AR', 'Arkansas', 'US', 'AR', 'South', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-CA', 'California', 'US', 'CA', 'Pacific', 'America/Los_Angeles', True, NULL, NOW(), NOW()),
('US-CO', 'Colorado', 'US', 'CO', 'Mountain', 'America/Denver', True, NULL, NOW(), NOW()),
('US-CT', 'Connecticut', 'US', 'CT', 'Northeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-DE', 'Delaware', 'US', 'DE', 'Mid-Atlantic', 'America/New_York', True, NULL, NOW(), NOW()),
('US-DC', 'District of Columbia', 'US', 'DC', 'Mid-Atlantic', 'America/New_York', True, NULL, NOW(), NOW()),
('US-FL', 'Florida', 'US', 'FL', 'Southeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-GA', 'Georgia', 'US', 'GA', 'Southeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-HI', 'Hawaii', 'US', 'HI', 'Pacific', 'Pacific/Honolulu', True, NULL, NOW(), NOW()),
('US-ID', 'Idaho', 'US', 'ID', 'Mountain', 'America/Denver', True, NULL, NOW(), NOW()),
('US-IL', 'Illinois', 'US', 'IL', 'Midwest', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-IN', 'Indiana', 'US', 'IN', 'Midwest', 'America/Indiana/Indianapolis', True, NULL, NOW(), NOW()),
('US-IA', 'Iowa', 'US', 'IA', 'Midwest', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-KS', 'Kansas', 'US', 'KS', 'Midwest', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-KY', 'Kentucky', 'US', 'KY', 'South', 'America/New_York', True, NULL, NOW(), NOW()),
('US-LA', 'Louisiana', 'US', 'LA', 'South', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-ME', 'Maine', 'US', 'ME', 'Northeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-MD', 'Maryland', 'US', 'MD', 'Mid-Atlantic', 'America/New_York', True, NULL, NOW(), NOW()),
('US-MA', 'Massachusetts', 'US', 'MA', 'Northeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-MI', 'Michigan', 'US', 'MI', 'Midwest', 'America/Detroit', True, NULL, NOW(), NOW()),
('US-MN', 'Minnesota', 'US', 'MN', 'Midwest', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-MS', 'Mississippi', 'US', 'MS', 'South', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-MO', 'Missouri', 'US', 'MO', 'Midwest', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-MT', 'Montana', 'US', 'MT', 'Mountain', 'America/Denver', True, NULL, NOW(), NOW()),
('US-NE', 'Nebraska', 'US', 'NE', 'Midwest', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-NV', 'Nevada', 'US', 'NV', 'Mountain', 'America/Los_Angeles', True, NULL, NOW(), NOW()),
('US-NH', 'New Hampshire', 'US', 'NH', 'Northeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-NJ', 'New Jersey', 'US', 'NJ', 'Mid-Atlantic', 'America/New_York', True, NULL, NOW(), NOW()),
('US-NM', 'New Mexico', 'US', 'NM', 'Southwest', 'America/Denver', True, NULL, NOW(), NOW()),
('US-NY', 'New York', 'US', 'NY', 'Northeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-NC', 'North Carolina', 'US', 'NC', 'Southeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-ND', 'North Dakota', 'US', 'ND', 'Midwest', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-OH', 'Ohio', 'US', 'OH', 'Midwest', 'America/New_York', True, NULL, NOW(), NOW()),
('US-OK', 'Oklahoma', 'US', 'OK', 'South', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-OR', 'Oregon', 'US', 'OR', 'Pacific', 'America/Los_Angeles', True, NULL, NOW(), NOW()),
('US-PA', 'Pennsylvania', 'US', 'PA', 'Northeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-RI', 'Rhode Island', 'US', 'RI', 'Northeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-SC', 'South Carolina', 'US', 'SC', 'Southeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-SD', 'South Dakota', 'US', 'SD', 'Midwest', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-TN', 'Tennessee', 'US', 'TN', 'South', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-TX', 'Texas', 'US', 'TX', 'South', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-UT', 'Utah', 'US', 'UT', 'Mountain', 'America/Denver', True, NULL, NOW(), NOW()),
('US-VT', 'Vermont', 'US', 'VT', 'Northeast', 'America/New_York', True, NULL, NOW(), NOW()),
('US-VA', 'Virginia', 'US', 'VA', 'Mid-Atlantic', 'America/New_York', True, NULL, NOW(), NOW()),
('US-WA', 'Washington', 'US', 'WA', 'Pacific', 'America/Los_Angeles', True, NULL, NOW(), NOW()),
('US-WV', 'West Virginia', 'US', 'WV', 'South', 'America/New_York', True, NULL, NOW(), NOW()),
('US-WI', 'Wisconsin', 'US', 'WI', 'Midwest', 'America/Chicago', True, NULL, NOW(), NOW()),
('US-WY', 'Wyoming', 'US', 'WY', 'Mountain', 'America/Denver', True, NULL, NOW(), NOW()),

-- CHINA
('CN-BJ', 'Beijing', 'CN', 'BJ', 'North China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-TJ', 'Tianjin', 'CN', 'TJ', 'North China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-SH', 'Shanghai', 'CN', 'SH', 'East China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-CQ', 'Chongqing', 'CN', 'CQ', 'Southwest China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-HE', 'Hebei', 'CN', 'HE', 'North China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-SX', 'Shanxi', 'CN', 'SX', 'North China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-LN', 'Liaoning', 'CN', 'LN', 'Northeast China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-JL', 'Jilin', 'CN', 'JL', 'Northeast China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-HL', 'Heilongjiang', 'CN', 'HL', 'Northeast China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-JS', 'Jiangsu', 'CN', 'JS', 'East China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-ZJ', 'Zhejiang', 'CN', 'ZJ', 'East China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-AH', 'Anhui', 'CN', 'AH', 'East China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-FJ', 'Fujian', 'CN', 'FJ', 'East China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-JX', 'Jiangxi', 'CN', 'JX', 'East China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-SD', 'Shandong', 'CN', 'SD', 'East China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-HA', 'Henan', 'CN', 'HA', 'Central China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-HB', 'Hubei', 'CN', 'HB', 'Central China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-HN', 'Hunan', 'CN', 'HN', 'Central China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-GD', 'Guangdong', 'CN', 'GD', 'South China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-GX', 'Guangxi', 'CN', 'GX', 'South China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-HI', 'Hainan', 'CN', 'HI', 'South China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-SC', 'Sichuan', 'CN', 'SC', 'Southwest China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-GZ', 'Guizhou', 'CN', 'GZ', 'Southwest China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-YN', 'Yunnan', 'CN', 'YN', 'Southwest China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-XZ', 'Tibet', 'CN', 'XZ', 'Southwest China', 'Asia/Urumqi', True, NULL, NOW(), NOW()),
('CN-SN', 'Shaanxi', 'CN', 'SN', 'Northwest China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-GS', 'Gansu', 'CN', 'GS', 'Northwest China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-QH', 'Qinghai', 'CN', 'QH', 'Northwest China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-NX', 'Ningxia', 'CN', 'NX', 'Northwest China', 'Asia/Shanghai', True, NULL, NOW(), NOW()),
('CN-XJ', 'Xinjiang', 'CN', 'XJ', 'Northwest China', 'Asia/Urumqi', True, NULL, NOW(), NOW()),
('CN-TW', 'Taiwan', 'CN', 'TW', 'East China', 'Asia/Taipei', True, NULL, NOW(), NOW()),
('CN-HK', 'Hong Kong', 'CN', 'HK', 'South China', 'Asia/Hong_Kong', True, NULL, NOW(), NOW()),
('CN-MO', 'Macau', 'CN', 'MO', 'South China', 'Asia/Macau', True, NULL, NOW(), NOW());