-- Gerado por split_schema_dump.py — NÃO editar manualmente; regenere a partir do dump.
-- Fase: 04_sequences_owned_by.sql
-- Execução: ver README.md e run_rebuild.sh

--
-- Name: action_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.action ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.action_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activity_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_key_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.api_key ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_key_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_permissions_revision_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.application_permissions_revision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_permissions_revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.auth_sessions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_sessions_id_seq OWNER TO admin;

--
-- Name: auth_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.auth_sessions_id_seq OWNED BY public.auth_sessions.id;


--
-- Name: bookmark_ordering_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.bookmark_ordering ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmark_ordering_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: capability_channel_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_channel_id_seq OWNER TO admin;

--
-- Name: capability_channel_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_channel_id_seq OWNED BY public.capability_channel.id;


--
-- Name: capability_context_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_context_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_context_id_seq OWNER TO admin;

--
-- Name: capability_context_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_context_id_seq OWNED BY public.capability_context.id;


--
-- Name: capability_country_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_country_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_country_id_seq OWNER TO admin;

--
-- Name: capability_country_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_country_id_seq OWNED BY public.capability_country.id;


--
-- Name: capability_locker_location_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_locker_location_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_locker_location_id_seq OWNER TO admin;

--
-- Name: capability_locker_location_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_locker_location_id_seq OWNED BY public.capability_locker_location.id;


--
-- Name: capability_profile_action_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_profile_action_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_profile_action_id_seq OWNER TO admin;

--
-- Name: capability_profile_action_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_profile_action_id_seq OWNED BY public.capability_profile_action.id;


--
-- Name: capability_profile_constraint_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_profile_constraint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_profile_constraint_id_seq OWNER TO admin;

--
-- Name: capability_profile_constraint_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_profile_constraint_id_seq OWNED BY public.capability_profile_constraint.id;


--
-- Name: capability_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_profile_id_seq OWNER TO admin;

--
-- Name: capability_profile_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_profile_id_seq OWNED BY public.capability_profile.id;


--
-- Name: capability_profile_method_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_profile_method_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_profile_method_id_seq OWNER TO admin;

--
-- Name: capability_profile_method_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_profile_method_id_seq OWNED BY public.capability_profile_method.id;


--
-- Name: capability_profile_method_interface_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_profile_method_interface_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_profile_method_interface_id_seq OWNER TO admin;

--
-- Name: capability_profile_method_interface_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_profile_method_interface_id_seq OWNED BY public.capability_profile_method_interface.id;


--
-- Name: capability_profile_method_requirement_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_profile_method_requirement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_profile_method_requirement_id_seq OWNER TO admin;

--
-- Name: capability_profile_method_requirement_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_profile_method_requirement_id_seq OWNED BY public.capability_profile_method_requirement.id;


--
-- Name: capability_profile_snapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_profile_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_profile_snapshot_id_seq OWNER TO admin;

--
-- Name: capability_profile_snapshot_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_profile_snapshot_id_seq OWNED BY public.capability_profile_snapshot_old.id;


--
-- Name: capability_profile_snapshot_id_seq1; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_profile_snapshot_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_profile_snapshot_id_seq1 OWNER TO admin;

--
-- Name: capability_profile_snapshot_id_seq1; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_profile_snapshot_id_seq1 OWNED BY public.capability_profile_snapshot.id;


--
-- Name: capability_profile_target_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_profile_target_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_profile_target_id_seq OWNER TO admin;

--
-- Name: capability_profile_target_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_profile_target_id_seq OWNED BY public.capability_profile_target.id;


--
-- Name: capability_province_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_province_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_province_id_seq OWNER TO admin;

--
-- Name: capability_province_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_province_id_seq OWNED BY public.capability_province.id;


--
-- Name: capability_region_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_region_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_region_id_seq OWNER TO admin;

--
-- Name: capability_region_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_region_id_seq OWNED BY public.capability_region.id;


--
-- Name: capability_requirement_catalog_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.capability_requirement_catalog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.capability_requirement_catalog_id_seq OWNER TO admin;

--
-- Name: capability_requirement_catalog_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.capability_requirement_catalog_id_seq OWNED BY public.capability_requirement_catalog.id;


--
-- Name: card_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.card_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: card_label_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.card_label ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_label_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.collection_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.collection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_permission_graph_revision_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.collection_permission_graph_revision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_permission_graph_revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: connection_impersonations_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.connection_impersonations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.connection_impersonations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.core_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dashboard_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.dashboard_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dashboard_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dashboard_favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.dashboard_favorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dashboard_favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dashboard_tab_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.dashboard_tab ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dashboard_tab_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dashboardcard_series_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.dashboardcard_series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dashboardcard_series_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demand_forecast_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.demand_forecast_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.demand_forecast_id_seq OWNER TO admin;

--
-- Name: demand_forecast_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.demand_forecast_id_seq OWNED BY public.demand_forecast.id;


--
-- Name: dependency_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.dependency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dependency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dimension_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.dimension ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dimension_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ellanlab_depreciation_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.ellanlab_depreciation_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.ellanlab_depreciation_schedule_id_seq OWNER TO admin;

--
-- Name: ellanlab_depreciation_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.ellanlab_depreciation_schedule_id_seq OWNED BY public.ellanlab_depreciation_schedule.id;


--
-- Name: ellanlab_monthly_pnl_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.ellanlab_monthly_pnl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.ellanlab_monthly_pnl_id_seq OWNER TO admin;

--
-- Name: ellanlab_monthly_pnl_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.ellanlab_monthly_pnl_id_seq OWNED BY public.ellanlab_monthly_pnl.id;


--
-- Name: ellanlab_revenue_recognition_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.ellanlab_revenue_recognition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.ellanlab_revenue_recognition_id_seq OWNER TO admin;

--
-- Name: ellanlab_revenue_recognition_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.ellanlab_revenue_recognition_id_seq OWNED BY public.ellanlab_revenue_recognition.id;


--
-- Name: financial_kpi_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.financial_kpi_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.financial_kpi_daily_id_seq OWNER TO admin;

--
-- Name: financial_kpi_daily_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.financial_kpi_daily_id_seq OWNED BY public.financial_kpi_daily.id;


--
-- Name: fiscal_auto_classification_log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.fiscal_auto_classification_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fiscal_auto_classification_log_id_seq OWNER TO admin;

--
-- Name: fiscal_auto_classification_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.fiscal_auto_classification_log_id_seq OWNED BY public.fiscal_auto_classification_log.id;


--
-- Name: fulfillment_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.fulfillment_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fulfillment_inventory_id_seq OWNER TO admin;

--
-- Name: fulfillment_inventory_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.fulfillment_inventory_id_seq OWNED BY public.fulfillment_inventory.id;


--
-- Name: group_table_access_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.sandboxes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_table_access_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: journal_entry_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.journal_entry_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.journal_entry_lines_id_seq OWNER TO admin;

--
-- Name: journal_entry_lines_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.journal_entry_lines_id_seq OWNED BY public.journal_entry_lines.id;


--
-- Name: label_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.label ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.label_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locker_slot_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.locker_slot_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.locker_slot_configs_id_seq OWNER TO admin;

--
-- Name: locker_slot_configs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.locker_slot_configs_id_seq OWNED BY public.locker_slot_configs.id;


--
-- Name: locker_slot_hourly_occupancy_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.locker_slot_hourly_occupancy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.locker_slot_hourly_occupancy_id_seq OWNER TO admin;

--
-- Name: locker_slot_hourly_occupancy_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.locker_slot_hourly_occupancy_id_seq OWNED BY public.locker_slot_hourly_occupancy.id;


--
-- Name: locker_telemetry_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.locker_telemetry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.locker_telemetry_id_seq OWNER TO admin;

--
-- Name: locker_telemetry_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.locker_telemetry_id_seq OWNED BY public.locker_telemetry.id;


--
-- Name: locker_telemetry_partitioned_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.locker_telemetry_partitioned_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.locker_telemetry_partitioned_id_seq OWNER TO admin;

--
-- Name: locker_utilization_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.locker_utilization_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.locker_utilization_snapshots_id_seq OWNER TO admin;

--
-- Name: locker_utilization_snapshots_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.locker_utilization_snapshots_id_seq OWNED BY public.locker_utilization_snapshots.id;


--
-- Name: login_history_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.login_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logistics_manifest_items_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.logistics_manifest_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.logistics_manifest_items_id_seq OWNER TO admin;

--
-- Name: logistics_manifest_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.logistics_manifest_items_id_seq OWNED BY public.logistics_manifest_items.id;


--
-- Name: metabase_database_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.metabase_database ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metabase_database_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metabase_field_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.metabase_field ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metabase_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metabase_fieldvalues_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.metabase_fieldvalues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metabase_fieldvalues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metabase_table_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.metabase_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metabase_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metric_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.metric ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metric_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metric_important_field_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.metric_important_field ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metric_important_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ml_features_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.ml_features_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.ml_features_daily_id_seq OWNER TO admin;

--
-- Name: ml_features_daily_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.ml_features_daily_id_seq OWNED BY public.ml_features_daily.id;


--
-- Name: ml_model_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.ml_model_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.ml_model_metadata_id_seq OWNER TO admin;

--
-- Name: ml_model_metadata_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.ml_model_metadata_id_seq OWNED BY public.ml_model_metadata.id;


--
-- Name: ml_predictions_log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.ml_predictions_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.ml_predictions_log_id_seq OWNER TO admin;

--
-- Name: ml_predictions_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.ml_predictions_log_id_seq OWNED BY public.ml_predictions_log.id;


--
-- Name: model_index_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.model_index ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_index_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: moderation_review_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.moderation_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moderation_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: native_query_snippet_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.native_query_snippet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.native_query_snippet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.notification_logs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.notification_logs_id_seq OWNER TO admin;

--
-- Name: notification_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.notification_logs_id_seq OWNED BY public.notification_logs.id;


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.order_items_id_seq OWNER TO admin;

--
-- Name: order_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.order_items_id_seq OWNED BY public.order_items.id;


--
-- Name: parameter_card_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.parameter_card ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parameter_card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_billing_line_items_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.partner_billing_line_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.partner_billing_line_items_id_seq OWNER TO admin;

--
-- Name: partner_billing_line_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.partner_billing_line_items_id_seq OWNED BY public.partner_billing_line_items.id;


--
-- Name: partner_integration_health_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.partner_integration_health_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.partner_integration_health_id_seq OWNER TO admin;

--
-- Name: partner_integration_health_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.partner_integration_health_id_seq OWNED BY public.partner_integration_health.id;


--
-- Name: partner_settlement_items_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.partner_settlement_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.partner_settlement_items_id_seq OWNER TO admin;

--
-- Name: partner_settlement_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.partner_settlement_items_id_seq OWNED BY public.partner_settlement_items.id;


--
-- Name: payment_interface_catalog_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.payment_interface_catalog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.payment_interface_catalog_id_seq OWNER TO admin;

--
-- Name: payment_interface_catalog_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.payment_interface_catalog_id_seq OWNED BY public.payment_interface_catalog.id;


--
-- Name: payment_method_catalog_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.payment_method_catalog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.payment_method_catalog_id_seq OWNER TO admin;

--
-- Name: payment_method_catalog_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.payment_method_catalog_id_seq OWNED BY public.payment_method_catalog.id;


--
-- Name: permissions_group_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.permissions_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions_group_membership_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.permissions_group_membership ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_group_membership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions_revision_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.permissions_revision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persisted_info_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.persisted_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persisted_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pickup_events_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.pickup_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.pickup_events_id_seq OWNER TO admin;

--
-- Name: pickup_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.pickup_events_id_seq OWNED BY public.pickup_events.id;


--
-- Name: price_history_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.price_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.price_history_id_seq OWNER TO admin;

--
-- Name: price_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.price_history_id_seq OWNED BY public.price_history.id;


--
-- Name: product_bundle_items_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.product_bundle_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.product_bundle_items_id_seq OWNER TO admin;

--
-- Name: product_bundle_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.product_bundle_items_id_seq OWNED BY public.product_bundle_items.id;


--
-- Name: product_locker_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.product_locker_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.product_locker_configs_id_seq OWNER TO admin;

--
-- Name: product_locker_configs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.product_locker_configs_id_seq OWNED BY public.product_locker_configs.id;


--
-- Name: product_recommendations_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.product_recommendations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.product_recommendations_id_seq OWNER TO admin;

--
-- Name: product_recommendations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.product_recommendations_id_seq OWNED BY public.product_recommendations.id;


--
-- Name: pulse_card_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.pulse_card ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pulse_card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pulse_channel_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.pulse_channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pulse_channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pulse_channel_recipient_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.pulse_channel_recipient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pulse_channel_recipient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pulse_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.pulse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pulse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: query_execution_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.query_execution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.query_execution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recent_views_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.recent_views ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recent_views_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_card_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.report_card ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_cardfavorite_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.report_cardfavorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_cardfavorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_dashboard_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.report_dashboard ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_dashboard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_dashboardcard_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.report_dashboardcard ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_dashboardcard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revision_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.revision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: secret_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.secret ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.secret_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: segment_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.segment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.segment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.store_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.store_inventory_id_seq OWNER TO admin;

--
-- Name: store_inventory_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.store_inventory_id_seq OWNED BY public.store_inventory.id;


--
-- Name: subscription_benefits_usage_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.subscription_benefits_usage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.subscription_benefits_usage_id_seq OWNER TO admin;

--
-- Name: subscription_benefits_usage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.subscription_benefits_usage_id_seq OWNED BY public.subscription_benefits_usage.id;


--
-- Name: subscription_usage_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.subscription_usage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.subscription_usage_id_seq OWNER TO admin;

--
-- Name: subscription_usage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.subscription_usage_id_seq OWNED BY public.subscription_usage.id;


--
-- Name: task_history_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.task_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timeline_event_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.timeline_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeline_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timeline_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.timeline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: view_log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


ALTER TABLE public.view_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.view_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_provider_catalog_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--


CREATE SEQUENCE public.wallet_provider_catalog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.wallet_provider_catalog_id_seq OWNER TO admin;

--
-- Name: wallet_provider_catalog_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--


ALTER SEQUENCE public.wallet_provider_catalog_id_seq OWNED BY public.wallet_provider_catalog.id;


