from typing import Literal

GatewayEventType = Literal[
    "GATEWAY_PAYMENT_RECEIVED",
    "GATEWAY_RISK_DECIDED",
    "GATEWAY_BACKEND_CALLED",
    "GATEWAY_PAYMENT_APPROVED",
    "GATEWAY_PAYMENT_CHALLENGE",
    "GATEWAY_PAYMENT_BLOCKED",
    "GATEWAY_BACKEND_FAILED",
    "GATEWAY_IDEMPOTENCY_REPLAY",
    "GATEWAY_IDEMPOTENCY_MISMATCH",
    "GATEWAY_INTERNAL_ERROR",
]