FROM postgis/postgis:15-3.4

# Instalar TimescaleDB
RUN apt-get update && \
    apt-get install -y gnupg curl lsb-release && \
    curl -s https://packagecloud.io/install/repositories/timescale/timescaledb/script.deb.sh | bash && \
    apt-get update && \
    apt-get install -y timescaledb-2-postgresql-15 postgresql-15-cron && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configurar extensões
RUN echo "ALTER SYSTEM SET shared_preload_libraries = 'timescaledb,pg_cron';" > /docker-entrypoint-initdb.d/00-config.sql && \
    echo "CREATE EXTENSION IF NOT EXISTS timescaledb;" >> /docker-entrypoint-initdb.d/01-timescaledb.sql && \
    echo "CREATE EXTENSION IF NOT EXISTS pg_cron;" >> /docker-entrypoint-initdb.d/02-pgcron.sql