#!/usr/bin/env bash
set -euo pipefail
export FEATURE_FREEZE_MONOLITH="${FEATURE_FREEZE_MONOLITH:-1}"
export MONOLITH_NEW_FEATURES_FROZEN="${MONOLITH_NEW_FEATURES_FROZEN:-1}"
echo "freeze_monolith: FEATURE_FREEZE_MONOLITH=$FEATURE_FREEZE_MONOLITH"
