# 01_source/backend/runtime/app/core/event_types.py
from enum import Enum


class Severity(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class EventType(str, Enum):
    # Venda
    SALE_STARTED = "SALE_STARTED"
    PAYMENT_APPROVED = "PAYMENT_APPROVED"
    PAYMENT_DENIED = "PAYMENT_DENIED"
    REFUND_ISSUED = "REFUND_ISSUED"

    # Hardware / Porta
    HW_OPEN_CMD_SENT = "HW_OPEN_CMD_SENT"
    DOOR_OPENED = "DOOR_OPENED"
    DOOR_CLOSED = "DOOR_CLOSED"

    # FSM
    STATE_CHANGE = "STATE_CHANGE"

    # Saúde / Infra
    ESP_HEARTBEAT = "ESP_HEARTBEAT"
    WIFI_RECONNECTED = "WIFI_RECONNECTED"
    ESP_REBOOTED = "ESP_REBOOTED"
    TEMP_READING = "TEMP_READING"
    TEMP_OUT_OF_RANGE = "TEMP_OUT_OF_RANGE"
    POWER_LOSS_DETECTED = "POWER_LOSS_DETECTED"

    # Erro genérico
    ERROR = "ERROR"


class ErrorCode(str, Enum):
    DOOR_OPEN_TIMEOUT = "DOOR_OPEN_TIMEOUT"
    DOOR_CLOSE_TIMEOUT = "DOOR_CLOSE_TIMEOUT"
    SENSOR_STUCK_OPEN = "SENSOR_STUCK_OPEN"
    SENSOR_STUCK_CLOSED = "SENSOR_STUCK_CLOSED"
    PAYMENT_CONFIRMED_BUT_NO_OPEN = "PAYMENT_CONFIRMED_BUT_NO_OPEN"
    OPENED_WITHOUT_AUTH = "OPENED_WITHOUT_AUTH"  # CRITICAL
    ESP_UNREACHABLE = "ESP_UNREACHABLE"
    TEMP_CRITICAL = "TEMP_CRITICAL"
    DB_WRITE_FAIL = "DB_WRITE_FAIL"
